//! Physics Collision Group schema.
//!
//! Defines a collision group for coarse filtering. When a collision occurs
//! between two objects that have a PhysicsCollisionGroup assigned, they will
//! collide with each other unless this PhysicsCollisionGroup pair is filtered.
//!
//! # C++ Reference
//!
//! Port of `pxr/usd/usdPhysics/collisionGroup.h` and `collisionGroup.cpp`
//!
//! # Usage
//!
//! ```ignore
//! use usd::usd_physics::CollisionGroup;
//!
//! // Create two collision groups
//! let group_a = CollisionGroup::define(&stage, &path_a)?;
//! let group_b = CollisionGroup::define(&stage, &path_b)?;
//!
//! // Filter collisions between groups
//! group_a.create_filtered_groups_rel()?.add_target(&path_b)?;
//! ```

use std::collections::{HashMap, HashSet};
use std::sync::Arc;

use usd_core::attribute::Variability;
use usd_core::{Attribute, Prim, Relationship, SchemaKind, Stage, Typed};
use usd_sdf::Path;
use usd_tf::Token;
use usd_vt::Value;

use super::tokens::USD_PHYSICS_TOKENS;

/// Collision group table for querying filter relationships.
///
/// Utility structure generated by `compute_collision_group_table()`.
/// Contains a table describing which pairs of collision groups have
/// collisions enabled/disabled by the filtering rules.
///
/// Uses an upper-triangular (diagonal) layout identical to C++:
/// table size = (n+1)*n/2, index = _get_table_index(min, max, n).
#[derive(Debug, Clone, Default)]
pub struct CollisionGroupTable {
    /// All collision groups in the table (in stage traversal order).
    groups: Vec<Path>,
    /// Upper-triangular collision enabled table.
    /// Size = (n+1)*n/2 where n = groups.len().
    /// Entry is false if collision is disabled.
    enabled: Vec<bool>,
}

impl CollisionGroupTable {
    /// Return the set of all CollisionGroup paths this table contains.
    pub fn get_collision_groups(&self) -> &[Path] {
        &self.groups
    }

    /// Compute the upper-triangular table index for (idx_a, idx_b).
    /// Identical to C++ `_GetCollisionTableIndex(minGroup, maxGroup, groupSize)`.
    fn table_index(idx_a: usize, idx_b: usize, n: usize) -> usize {
        let min = idx_a.min(idx_b);
        let max = idx_a.max(idx_b);
        // skip = min*(min+1)/2 entries in the rows above
        let num_skipped = (min * min + min) / 2;
        min * n - num_skipped + max
    }

    /// Return true if the groups at indices `idx_a` and `idx_b` collide.
    ///
    /// Out-of-bounds indices return true (default enabled), matching C++.
    pub fn is_collision_enabled_by_index(&self, idx_a: usize, idx_b: usize) -> bool {
        let n = self.groups.len();
        if idx_a >= n || idx_b >= n {
            // Groups not in table -> default enabled
            return true;
        }
        let index = Self::table_index(idx_a, idx_b, n);
        self.enabled.get(index).copied().unwrap_or(true)
    }

    /// Return true if the groups at paths `prim_a` and `prim_b` collide.
    pub fn is_collision_enabled(&self, prim_a: &Path, prim_b: &Path) -> bool {
        let idx_a = self.groups.iter().position(|p| p == prim_a);
        let idx_b = self.groups.iter().position(|p| p == prim_b);

        match (idx_a, idx_b) {
            (Some(a), Some(b)) => self.is_collision_enabled_by_index(a, b),
            _ => true, // Default to enabled for unknown groups
        }
    }
}

/// Physics collision group schema.
///
/// Defines a collision group for coarse filtering. When a collision
/// occurs between two objects that have a PhysicsCollisionGroup assigned,
/// they will collide with each other unless this PhysicsCollisionGroup pair
/// is filtered. See filteredGroups attribute.
///
/// A CollectionAPI:colliders maintains a list of PhysicsCollisionAPI rel-s
/// that defines the members of this CollisionGroup.
///
/// # Schema Kind
///
/// This is a concrete typed schema (ConcreteTyped).
///
/// # C++ Reference
///
/// Port of `UsdPhysicsCollisionGroup` class.
#[derive(Debug, Clone)]
pub struct CollisionGroup {
    prim: Prim,
}

impl CollisionGroup {
    /// The schema kind for this class.
    pub const SCHEMA_KIND: SchemaKind = SchemaKind::ConcreteTyped;

    /// The schema type name.
    pub const SCHEMA_TYPE_NAME: &'static str = "PhysicsCollisionGroup";

    // =========================================================================
    // Construction
    // =========================================================================

    /// Construct a CollisionGroup on the given prim.
    pub fn new(prim: Prim) -> Self {
        Self { prim }
    }

    /// Construct a CollisionGroup from another prim.
    pub fn from_prim(prim: &Prim) -> Self {
        Self::new(prim.clone())
    }

    /// Return a CollisionGroup holding the prim at `path` on `stage`.
    pub fn get(stage: &Arc<Stage>, path: &Path) -> Option<Self> {
        let prim = stage.get_prim_at_path(path)?;
        if prim.is_a(&Token::new(Self::SCHEMA_TYPE_NAME)) {
            Some(Self::new(prim))
        } else {
            None
        }
    }

    /// Attempt to ensure a prim adhering to this schema at `path`
    /// is defined on this stage.
    pub fn define(stage: &Arc<Stage>, path: &Path) -> Option<Self> {
        let prim = stage
            .define_prim(path.to_string(), Self::SCHEMA_TYPE_NAME)
            .ok()?;
        Some(Self::new(prim))
    }

    /// Returns the schema kind.
    pub fn get_schema_kind(&self) -> SchemaKind {
        Self::SCHEMA_KIND
    }

    // =========================================================================
    // MergeGroupName Attribute
    // =========================================================================

    /// If non-empty, any collision groups in a stage with a matching
    /// mergeGroup should be considered to refer to the same collection.
    ///
    /// Matching collision groups should behave as if there were a single
    /// group containing referenced colliders and filter groups from both.
    ///
    /// | Property | Value |
    /// |----------|-------|
    /// | Declaration | `string physics:mergeGroup` |
    /// | C++ Type | std::string |
    pub fn get_merge_group_name_attr(&self) -> Option<Attribute> {
        self.prim
            .get_attribute(USD_PHYSICS_TOKENS.physics_merge_group.as_str())
    }

    /// Creates the mergeGroup attribute.
    pub fn create_merge_group_name_attr(&self, default_value: Option<String>) -> Option<Attribute> {
        let attr = self.prim.create_attribute(
            USD_PHYSICS_TOKENS.physics_merge_group.as_str(),
            &usd_sdf::ValueTypeRegistry::instance().find_type_by_token(&Token::new("string")),
            false,
            Some(Variability::Varying),
        )?;

        if let Some(value) = default_value {
            attr.set(Value::from(value), usd_sdf::TimeCode::default());
        }

        Some(attr)
    }

    // =========================================================================
    // InvertFilteredGroups Attribute
    // =========================================================================

    /// Normally, the filter will disable collisions against the selected
    /// filter groups. However, if this option is set, the filter will disable
    /// collisions against all colliders except for those in the selected
    /// filter groups.
    ///
    /// | Property | Value |
    /// |----------|-------|
    /// | Declaration | `bool physics:invertFilteredGroups` |
    /// | C++ Type | bool |
    pub fn get_invert_filtered_groups_attr(&self) -> Option<Attribute> {
        self.prim
            .get_attribute(USD_PHYSICS_TOKENS.physics_invert_filtered_groups.as_str())
    }

    /// Creates the invertFilteredGroups attribute.
    pub fn create_invert_filtered_groups_attr(
        &self,
        default_value: Option<bool>,
    ) -> Option<Attribute> {
        let attr = self.prim.create_attribute(
            USD_PHYSICS_TOKENS.physics_invert_filtered_groups.as_str(),
            &usd_sdf::ValueTypeRegistry::instance().find_type_by_token(&Token::new("bool")),
            false,
            Some(Variability::Varying),
        )?;

        if let Some(value) = default_value {
            attr.set(Value::from(value), usd_sdf::TimeCode::default());
        }

        Some(attr)
    }

    // =========================================================================
    // FilteredGroups Relationship
    // =========================================================================

    /// References a list of PhysicsCollisionGroups with which
    /// collisions should be ignored.
    pub fn get_filtered_groups_rel(&self) -> Option<Relationship> {
        self.prim
            .get_relationship(USD_PHYSICS_TOKENS.physics_filtered_groups.as_str())
    }

    /// Creates the filteredGroups relationship.
    pub fn create_filtered_groups_rel(&self) -> Option<Relationship> {
        self.prim
            .create_relationship(USD_PHYSICS_TOKENS.physics_filtered_groups.as_str(), false)
    }

    // =========================================================================
    // CollectionAPI Access
    // =========================================================================

    /// Return the UsdCollectionAPI interface used for defining
    /// what colliders belong to this CollisionGroup.
    ///
    /// The collection is named "colliders" and maintained on the same prim.
    ///
    /// Matches C++ `UsdPhysicsCollisionGroup::GetCollidersCollectionAPI()`.
    pub fn get_colliders_collection_api(&self) -> Option<CollisionGroupCollectionAPI> {
        if !self.prim.is_valid() {
            return None;
        }
        Some(CollisionGroupCollectionAPI {
            prim: self.prim.clone(),
            collection_name: Token::new("colliders"),
        })
    }

    // =========================================================================
    // Custom Methods
    // =========================================================================

    /// Compute a table encoding all the collision groups filter rules for a stage.
    ///
    /// Handles merge groups (physics:mergeGroup) and inverted filters
    /// (physics:invertFilteredGroups). The returned table is diagonally
    /// symmetric using an upper-triangular layout.
    ///
    /// Matches C++ `UsdPhysicsCollisionGroup::ComputeCollisionGroupTable()`.
    pub fn compute_collision_group_table(stage: &Arc<Stage>) -> CollisionGroupTable {
        // Step 1: Collect all collision groups in stage traversal order.
        // PrimRange implements IntoIterator (not Iterator), so use into_iter().
        let schema_type = Token::new(CollisionGroup::SCHEMA_TYPE_NAME);
        let all_groups: Vec<CollisionGroup> = stage
            .traverse()
            .into_iter()
            .filter(|p| p.get_type_name() == schema_type)
            .map(CollisionGroup::new)
            .collect();

        // Step 2: Assign logical indices, merging groups with the same mergeGroup name.
        // Groups sharing a mergeGroup name get the same logical index.
        let mut prim_path_to_index: HashMap<Path, usize> = HashMap::new();
        let mut merge_group_to_index: HashMap<String, usize> = HashMap::new();
        let mut next_id: usize = 0;

        for cg in &all_groups {
            let path = cg.prim.get_path().clone();
            // C++: if mergeGroupAttr is NOT authored -> unique id.
            // If authored, use mergeGroupName as key (even empty string merges groups).
            let authored_merge_name: Option<String> =
                cg.get_merge_group_name_attr().and_then(|attr| {
                    if attr.has_authored_value_opinion() {
                        attr.get(usd_sdf::TimeCode::default())
                            .and_then(|v| v.downcast_clone::<String>())
                    } else {
                        None
                    }
                });

            if let Some(name) = authored_merge_name {
                // Authored merge group (any string, including empty) -> merge by name
                let id = *merge_group_to_index.entry(name).or_insert_with(|| {
                    let id = next_id;
                    next_id += 1;
                    id
                });
                prim_path_to_index.insert(path, id);
            } else {
                // Not authored -> unique index
                prim_path_to_index.insert(path, next_id);
                next_id += 1;
            }
        }

        // Step 3: Build merged collision table (size = next_id), all enabled.
        let merged_n = next_id;
        let merged_table_size = (merged_n + 1) * merged_n / 2;
        let mut merged: Vec<bool> = vec![true; merged_table_size];

        for cg_a in &all_groups {
            let path_a = cg_a.prim.get_path();
            let idx_a = prim_path_to_index[path_a];

            // Collect filtered group logical indices
            let filtered_indices: Vec<usize> = cg_a
                .get_filtered_groups_rel()
                .map(|rel| {
                    rel.get_targets()
                        .into_iter()
                        .filter_map(|p| prim_path_to_index.get(&p).copied())
                        .collect()
                })
                .unwrap_or_default();

            // Check invertFilteredGroups (only applies when authored)
            let inverted = cg_a
                .get_invert_filtered_groups_attr()
                .and_then(|attr| {
                    if attr.has_authored_value_opinion() {
                        attr.get(usd_sdf::TimeCode::default())
                            .and_then(|v| v.downcast_clone::<bool>())
                    } else {
                        None
                    }
                })
                .unwrap_or(false);

            if !inverted {
                // Normal: disable collision against filteredTargets
                for idx_b in &filtered_indices {
                    let min = idx_a.min(*idx_b);
                    let max = idx_a.max(*idx_b);
                    let ti = CollisionGroupTable::table_index(min, max, merged_n);
                    merged[ti] = false;
                }
            } else {
                // Inverted: disable collision against ALL except filteredTargets
                let allowed: HashSet<usize> = filtered_indices.into_iter().collect();
                for idx_b in 0..merged_n {
                    if !allowed.contains(&idx_b) {
                        let min = idx_a.min(idx_b);
                        let max = idx_a.max(idx_b);
                        let ti = CollisionGroupTable::table_index(min, max, merged_n);
                        merged[ti] = false;
                    }
                }
            }
        }

        // Step 4: Build output table (one entry per actual prim, not logical index).
        let out_n = all_groups.len();
        let out_size = (out_n + 1) * out_n / 2;
        let mut res = CollisionGroupTable {
            groups: all_groups
                .iter()
                .map(|cg| cg.prim.get_path().clone())
                .collect(),
            enabled: vec![true; out_size],
        };

        for i_a in 0..out_n {
            for i_b in i_a..out_n {
                let logical_a = prim_path_to_index[all_groups[i_a].prim.get_path()];
                let logical_b = prim_path_to_index[all_groups[i_b].prim.get_path()];
                let min_l = logical_a.min(logical_b);
                let max_l = logical_a.max(logical_b);
                let merged_ti = CollisionGroupTable::table_index(min_l, max_l, merged_n);
                let out_ti = CollisionGroupTable::table_index(i_a, i_b, out_n);
                res.enabled[out_ti] = merged[merged_ti];
            }
        }

        res
    }

    // =========================================================================
    // Schema attribute names
    // =========================================================================

    /// Returns all pre-declared attributes for this schema class.
    pub fn get_schema_attribute_names(include_inherited: bool) -> Vec<Token> {
        let mut names = if include_inherited {
            Typed::get_schema_attribute_names(true)
        } else {
            Vec::new()
        };

        names.extend([
            USD_PHYSICS_TOKENS.physics_merge_group.clone(),
            USD_PHYSICS_TOKENS.physics_invert_filtered_groups.clone(),
        ]);

        names
    }
}

impl CollisionGroup {
    /// Get the wrapped prim.
    pub fn get_prim(&self) -> &Prim {
        &self.prim
    }
}

// ============================================================================
// From implementations
// ============================================================================

impl From<Prim> for CollisionGroup {
    fn from(prim: Prim) -> Self {
        Self::new(prim)
    }
}

impl From<CollisionGroup> for Prim {
    fn from(group: CollisionGroup) -> Self {
        group.prim
    }
}

impl AsRef<Prim> for CollisionGroup {
    fn as_ref(&self) -> &Prim {
        &self.prim
    }
}

// ============================================================================
// CollisionGroupCollectionAPI
// ============================================================================

/// Lightweight wrapper representing the CollectionAPI:colliders interface
/// on a CollisionGroup prim.
///
/// Matches C++ `UsdCollectionAPI` returned by
/// `UsdPhysicsCollisionGroup::GetCollidersCollectionAPI()`.
#[derive(Debug, Clone)]
pub struct CollisionGroupCollectionAPI {
    prim: Prim,
    collection_name: Token,
}

impl CollisionGroupCollectionAPI {
    /// Returns the collection name ("colliders").
    pub fn get_name(&self) -> &Token {
        &self.collection_name
    }

    /// Returns the wrapped prim.
    pub fn get_prim(&self) -> &Prim {
        &self.prim
    }

    /// Returns the includes relationship for this collection.
    pub fn get_includes_rel(&self) -> Option<Relationship> {
        let rel_name = format!("collection:{}:includes", self.collection_name.get_text());
        self.prim.get_relationship(&rel_name)
    }

    /// Returns the excludes relationship for this collection.
    pub fn get_excludes_rel(&self) -> Option<Relationship> {
        let rel_name = format!("collection:{}:excludes", self.collection_name.get_text());
        self.prim.get_relationship(&rel_name)
    }

    /// Returns the expansion rule attribute for this collection.
    pub fn get_expansion_rule_attr(&self) -> Option<Attribute> {
        let attr_name = format!(
            "collection:{}:expansionRule",
            self.collection_name.get_text()
        );
        self.prim.get_attribute(&attr_name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_schema_kind() {
        assert_eq!(CollisionGroup::SCHEMA_KIND, SchemaKind::ConcreteTyped);
    }

    #[test]
    fn test_schema_type_name() {
        assert_eq!(CollisionGroup::SCHEMA_TYPE_NAME, "PhysicsCollisionGroup");
    }

    #[test]
    fn test_collision_group_table_default() {
        let table = CollisionGroupTable::default();
        assert!(table.get_collision_groups().is_empty());
    }

    #[test]
    fn test_schema_attribute_names() {
        let names = CollisionGroup::get_schema_attribute_names(false);
        assert!(names.iter().any(|n| n.get_text() == "physics:mergeGroup"));
        assert!(
            names
                .iter()
                .any(|n| n.get_text() == "physics:invertFilteredGroups")
        );
    }

    // -------------------------------------------------------------------------
    // CollisionGroupTable unit tests — test the table logic directly by
    // constructing it manually (bypassing stage traversal).
    // -------------------------------------------------------------------------

    /// Build a CollisionGroupTable manually for N groups with given filter rules.
    ///
    /// `filter_pairs` is a list of (a, b) index pairs where collision is disabled.
    /// Uses the upper-triangular layout matching C++: size = (n+1)*n/2.
    fn make_table(n: usize, filter_pairs: &[(usize, usize)]) -> CollisionGroupTable {
        let groups: Vec<Path> = (0..n)
            .map(|i| Path::from_string(&format!("/Group{}", i)).unwrap())
            .collect();
        let tri_size = (n + 1) * n / 2;
        let mut enabled = vec![true; tri_size];
        for &(a, b) in filter_pairs {
            // Store only upper-triangle (min, max)
            let ti = CollisionGroupTable::table_index(a, b, n);
            enabled[ti] = false;
        }
        CollisionGroupTable { groups, enabled }
    }

    #[test]
    fn test_table_two_groups_no_filter() {
        // 2 groups, no filter: all pairs enabled
        let table = make_table(2, &[]);
        assert!(table.is_collision_enabled_by_index(0, 0));
        assert!(table.is_collision_enabled_by_index(0, 1));
        assert!(table.is_collision_enabled_by_index(1, 0));
        assert!(table.is_collision_enabled_by_index(1, 1));
    }

    #[test]
    fn test_table_two_groups_filtered() {
        // Groups 0 and 1 are filtered: collision disabled
        let table = make_table(2, &[(0, 1)]);
        assert!(!table.is_collision_enabled_by_index(0, 1));
        assert!(!table.is_collision_enabled_by_index(1, 0)); // symmetric
        assert!(table.is_collision_enabled_by_index(0, 0)); // self still enabled
        assert!(table.is_collision_enabled_by_index(1, 1));
    }

    #[test]
    fn test_table_three_groups_merge_scenario() {
        // 3 groups; groups 0 and 2 are filtered against group 1.
        // This simulates the "merge groups" logical index scenario:
        // mergeGroup="A" assigned to group 0 and group 2 -> they act as one.
        // Group 1 filters the merged group -> both (0,1) and (2,1) disabled.
        let table = make_table(3, &[(0, 1), (2, 1)]);

        assert!(!table.is_collision_enabled_by_index(0, 1));
        assert!(!table.is_collision_enabled_by_index(1, 0));
        assert!(!table.is_collision_enabled_by_index(2, 1));
        assert!(!table.is_collision_enabled_by_index(1, 2));

        // (0, 2) is not filtered
        assert!(table.is_collision_enabled_by_index(0, 2));
        assert!(table.is_collision_enabled_by_index(2, 0));
    }

    #[test]
    fn test_table_invert_filtered_groups_semantic() {
        // invertFilteredGroups: group 0 disables all EXCEPT group 1.
        // Equivalent to filtering (0,2), (0,3), ... for n=4
        let table = make_table(4, &[(0, 2), (0, 3)]);

        // (0, 1) remains enabled (the "allowed" group)
        assert!(table.is_collision_enabled_by_index(0, 1));
        assert!(table.is_collision_enabled_by_index(1, 0));

        // (0, 2) and (0, 3) are disabled
        assert!(!table.is_collision_enabled_by_index(0, 2));
        assert!(!table.is_collision_enabled_by_index(0, 3));

        // (1, 2) is unaffected
        assert!(table.is_collision_enabled_by_index(1, 2));
    }

    #[test]
    fn test_table_is_collision_enabled_by_path() {
        let table = make_table(3, &[(0, 2)]);
        let group0 = Path::from_string("/Group0").unwrap();
        let group1 = Path::from_string("/Group1").unwrap();
        let group2 = Path::from_string("/Group2").unwrap();

        assert!(table.is_collision_enabled(&group0, &group1));
        assert!(!table.is_collision_enabled(&group0, &group2));
        assert!(!table.is_collision_enabled(&group2, &group0)); // symmetric

        // Unknown group -> defaults to enabled
        let unknown = Path::from_string("/Unknown").unwrap();
        assert!(table.is_collision_enabled(&group0, &unknown));
    }

    #[test]
    fn test_table_out_of_bounds_index() {
        let table = make_table(2, &[]);
        // Out-of-bounds indices must return true (default enabled)
        assert!(table.is_collision_enabled_by_index(0, 99));
        assert!(table.is_collision_enabled_by_index(99, 0));
    }

    #[test]
    fn test_table_n_groups_all_filtered() {
        // n groups, every pair filtered
        let n = 4;
        let mut pairs = Vec::new();
        for i in 0..n {
            for j in (i + 1)..n {
                pairs.push((i, j));
            }
        }
        let table = make_table(n, &pairs);
        for i in 0..n {
            for j in 0..n {
                if i != j {
                    assert!(
                        !table.is_collision_enabled_by_index(i, j),
                        "({}, {}) should be disabled",
                        i,
                        j
                    );
                }
            }
        }
    }
}
