// Port of testenv/testArDefaultResolver.cpp
// Tests ArDefaultResolver: OpenAsset, GetBuffer, Read, GetFileUnsafe

use std::io::Write;

use usd_ar::{Asset, FilesystemAsset, ResolvedPath, get_resolver};

#[test]
fn test_open_asset() {
    // Write content to a temporary file
    let mut tmp = tempfile::NamedTempFile::new().expect("failed to create temp file");
    let contents = b"Test file generated by test_default_resolver_rs";
    tmp.write_all(contents).expect("write failed");
    tmp.flush().expect("flush failed");

    let tmp_path = tmp.path().to_string_lossy().to_string();

    // Open via ArGetResolver().OpenAsset(ArResolvedPath(tmpPath))
    let resolver = get_resolver().read().expect("rwlock poisoned");
    let resolved = ResolvedPath::new(&tmp_path);
    let asset = resolver
        .open_asset(&resolved)
        .expect("OpenAsset returned None");

    // Verify size matches file length and content length
    let asset_size = asset.size();
    let file_len = std::fs::metadata(&tmp_path).expect("metadata failed").len() as usize;
    assert_eq!(asset_size, file_len);
    assert_eq!(asset_size, contents.len());

    // GetBuffer: read entire contents
    let buffer = asset.get_buffer().expect("GetBuffer returned None");
    assert_eq!(&*buffer, contents);

    // Read: full read from offset 0
    let mut array = vec![0u8; asset_size];
    let read_count = asset.read(&mut array, 0);
    assert_eq!(read_count, asset_size);
    assert_eq!(&array, contents);

    // Read: partial read at offset
    let mut partial = vec![0u8; 5];
    let read_count = asset.read(&mut partial, 10);
    assert_eq!(read_count, 5);
    assert_eq!(&partial, &contents[10..15]);

    // GetFileUnsafe: should return a valid handle for filesystem assets
    let file_unsafe = asset.get_file_unsafe();
    assert!(
        file_unsafe.is_some(),
        "GetFileUnsafe should return Some for filesystem assets"
    );
    let (_, offset) = file_unsafe.expect("just checked");
    assert_eq!(offset, 0);
}

#[test]
fn test_resolve_existing_file() {
    let mut tmp = tempfile::NamedTempFile::new().expect("failed to create temp file");
    tmp.write_all(b"hello").expect("write failed");
    tmp.flush().expect("flush failed");

    let tmp_path = tmp.path().to_string_lossy().to_string();

    let resolver = get_resolver().read().expect("rwlock poisoned");
    let resolved = resolver.resolve(&tmp_path);
    assert!(!resolved.is_empty(), "resolve() should find existing file");
}

#[test]
fn test_resolve_nonexistent_file() {
    let resolver = get_resolver().read().expect("rwlock poisoned");
    let resolved = resolver.resolve("/absolutely/nonexistent/path/to/file.usd");
    assert!(
        resolved.is_empty(),
        "resolve() should return empty for nonexistent file"
    );
}

#[test]
fn test_create_identifier() {
    let resolver = get_resolver().read().expect("rwlock poisoned");

    // Absolute path should be returned as-is
    let id = resolver.create_identifier("/absolute/path/to/model.usd", None);
    assert_eq!(id, "/absolute/path/to/model.usd");
}

#[test]
fn test_create_identifier_with_anchor() {
    let resolver = get_resolver().read().expect("rwlock poisoned");

    // Relative path anchored to an absolute resolved path
    let anchor = ResolvedPath::new("/base/dir/scene.usd");
    let id = resolver.create_identifier("model.usd", Some(&anchor));
    // Should resolve relative to anchor's directory
    assert!(id.contains("model.usd"));
}

#[test]
fn test_get_extension() {
    let resolver = get_resolver().read().expect("rwlock poisoned");

    assert_eq!(resolver.get_extension("model.usd"), "usd");
    assert_eq!(resolver.get_extension("scene.usda"), "usda");
    assert_eq!(resolver.get_extension("archive.usdz"), "usdz");
    assert_eq!(resolver.get_extension("no_extension"), "");
}

#[test]
fn test_get_modification_timestamp() {
    let mut tmp = tempfile::NamedTempFile::new().expect("failed to create temp file");
    tmp.write_all(b"timestamp test").expect("write failed");
    tmp.flush().expect("flush failed");

    let tmp_path = tmp.path().to_string_lossy().to_string();

    let resolver = get_resolver().read().expect("rwlock poisoned");
    let resolved = ResolvedPath::new(&tmp_path);
    let timestamp = resolver.get_modification_timestamp(&tmp_path, &resolved);
    assert!(
        timestamp.is_valid(),
        "timestamp should be valid for existing file"
    );
}

#[test]
fn test_get_modification_timestamp_nonexistent() {
    let resolver = get_resolver().read().expect("rwlock poisoned");
    let resolved = ResolvedPath::new("/nonexistent/file.usd");
    let timestamp = resolver.get_modification_timestamp("/nonexistent/file.usd", &resolved);
    assert!(
        !timestamp.is_valid(),
        "timestamp should be invalid for nonexistent file"
    );
}

#[test]
fn test_open_asset_none_for_nonexistent() {
    let resolver = get_resolver().read().expect("rwlock poisoned");
    let resolved = ResolvedPath::new("/nonexistent/path/to/asset.usd");
    let asset = resolver.open_asset(&resolved);
    assert!(
        asset.is_none(),
        "OpenAsset should return None for nonexistent file"
    );
}

#[test]
fn test_detached_asset() {
    let mut tmp = tempfile::NamedTempFile::new().expect("failed to create temp file");
    let contents = b"detach test data";
    tmp.write_all(contents).expect("write failed");
    tmp.flush().expect("flush failed");

    let asset = FilesystemAsset::open(tmp.path()).expect("open failed");
    let detached = asset.get_detached().expect("get_detached failed");

    // Detached asset should have same size and contents
    assert_eq!(detached.size(), contents.len());
    let buf = detached.get_buffer().expect("buffer failed");
    assert_eq!(&*buf, contents);

    // Detached should be independent — drop original file
    drop(tmp);
    // Detached should still work
    assert_eq!(detached.size(), contents.len());
}
