//! Static token definitions.
//!
//! This module provides macros for declaring collections of static tokens.
//! Static tokens are pre-defined interned strings that are commonly used
//! throughout a codebase.
//!
//! # Why Static Tokens?
//!
//! Creating tokens at runtime has some overhead (hash lookup, potential
//! allocation). For frequently used tokens, it's more efficient to create
//! them once at startup and reuse them.
//!
//! # Examples
//!
//! ```
//! use usd_tf::define_tokens;
//! use usd_tf::Token;
//!
//! // Define a group of related tokens
//! define_tokens! {
//!     /// Tokens for geometry attributes
//!     pub GeomTokens {
//!         points,
//!         normals,
//!         colors,
//!         // Token with different string representation
//!         uv_coords => "st",
//!     }
//! }
//!
//! // Access tokens
//! let points = GeomTokens::points();
//! let normals = GeomTokens::normals();
//! let st = GeomTokens::uv_coords();
//!
//! assert_eq!(points.as_str(), "points");
//! assert_eq!(st.as_str(), "st");
//!
//! // Get all tokens in the group
//! let all = GeomTokens::all_tokens();
//! assert!(all.contains(&points));
//! ```

use crate::Token;

/// A group of related static tokens.
///
/// This trait is implemented by the structs generated by [`define_tokens!`].
pub trait StaticTokens: Sized {
    /// Get all tokens in this group.
    fn all_tokens() -> &'static [Token];
}

/// Macro to define a group of static tokens.
///
/// # Syntax
///
/// ```ignore
/// define_tokens! {
///     /// Optional doc comment
///     [pub] TokenGroupName {
///         token_name,                    // Token with same string value
///         other_name => "string_value",  // Token with different string
///     }
/// }
/// ```
///
/// # Examples
///
/// ```
/// use usd_tf::define_tokens;
/// use usd_tf::Token;
///
/// define_tokens! {
///     /// Schema tokens
///     pub SchemaTokens {
///         xform,
///         mesh,
///         scope,
///         prim_type => "primType",
///     }
/// }
///
/// assert_eq!(SchemaTokens::xform().as_str(), "xform");
/// assert_eq!(SchemaTokens::prim_type().as_str(), "primType");
/// ```
#[macro_export]
macro_rules! define_tokens {
    // Public visibility with doc comment
    (
        $(#[$meta:meta])*
        pub $name:ident {
            $($token:ident $(=> $str:literal)?),* $(,)?
        }
    ) => {
        $crate::_define_tokens_impl_pub! {
            $(#[$meta])*
            $name { $($token $(=> $str)?),* }
        }
    };

    // Private visibility with doc comment
    (
        $(#[$meta:meta])*
        $name:ident {
            $($token:ident $(=> $str:literal)?),* $(,)?
        }
    ) => {
        $crate::_define_tokens_impl_priv! {
            $(#[$meta])*
            $name { $($token $(=> $str)?),* }
        }
    };
}

/// Internal implementation macro for define_tokens - public version.
#[macro_export]
#[doc(hidden)]
macro_rules! _define_tokens_impl_pub {
    (
        $(#[$meta:meta])*
        $name:ident {
            $($token:ident $(=> $str:literal)?),* $(,)?
        }
    ) => {
        $(#[$meta])*
        pub struct $name;

        impl $name {
            $(
                /// Get the token.
                #[inline]
                pub fn $token() -> $crate::Token {
                    static TOKEN: std::sync::OnceLock<$crate::Token> = std::sync::OnceLock::new();
                    TOKEN.get_or_init(|| {
                        $crate::_define_tokens_str!($token $(=> $str)?)
                    }).clone()
                }
            )*

            /// Get all tokens in this group.
            #[inline]
            pub fn all_tokens() -> &'static [$crate::Token] {
                static TOKENS: std::sync::OnceLock<Vec<$crate::Token>> = std::sync::OnceLock::new();
                TOKENS.get_or_init(|| {
                    vec![
                        $(Self::$token(),)*
                    ]
                })
            }

            /// Get the number of tokens in this group.
            #[inline]
            pub fn count() -> usize {
                $crate::_define_tokens_count!($($token),*)
            }
        }

        impl $crate::static_tokens::StaticTokens for $name {
            fn all_tokens() -> &'static [$crate::Token] {
                $name::all_tokens()
            }
        }
    };
}

/// Internal implementation macro for define_tokens - private version.
#[macro_export]
#[doc(hidden)]
macro_rules! _define_tokens_impl_priv {
    (
        $(#[$meta:meta])*
        $name:ident {
            $($token:ident $(=> $str:literal)?),* $(,)?
        }
    ) => {
        $(#[$meta])*
        struct $name;

        impl $name {
            $(
                /// Get the token.
                #[inline]
                fn $token() -> $crate::Token {
                    static TOKEN: std::sync::OnceLock<$crate::Token> = std::sync::OnceLock::new();
                    TOKEN.get_or_init(|| {
                        $crate::_define_tokens_str!($token $(=> $str)?)
                    }).clone()
                }
            )*

            /// Get all tokens in this group.
            #[inline]
            fn all_tokens() -> &'static [$crate::Token] {
                static TOKENS: std::sync::OnceLock<Vec<$crate::Token>> = std::sync::OnceLock::new();
                TOKENS.get_or_init(|| {
                    vec![
                        $(Self::$token(),)*
                    ]
                })
            }

            /// Get the number of tokens in this group.
            #[inline]
            fn count() -> usize {
                $crate::_define_tokens_count!($($token),*)
            }
        }

        impl $crate::static_tokens::StaticTokens for $name {
            fn all_tokens() -> &'static [$crate::Token] {
                $name::all_tokens()
            }
        }
    };
}

/// Helper macro to get the string for a token.
#[macro_export]
#[doc(hidden)]
macro_rules! _define_tokens_str {
    ($token:ident => $str:literal) => {
        $crate::Token::new($str)
    };
    ($token:ident) => {
        $crate::Token::new(stringify!($token))
    };
}

/// Helper macro to count tokens.
#[macro_export]
#[doc(hidden)]
macro_rules! _define_tokens_count {
    () => { 0usize };
    ($first:ident $(, $rest:ident)*) => {
        1usize + $crate::_define_tokens_count!($($rest),*)
    };
}

/// Convenience macro for defining private tokens within a module.
///
/// This is useful when tokens are only used within a single file.
///
/// # Examples
///
/// ```
/// use usd_tf::define_private_tokens;
/// use usd_tf::Token;
///
/// define_private_tokens! {
///     LocalTokens {
///         internal_value,
///         helper_attr => "_helper",
///     }
/// }
///
/// fn use_tokens() {
///     let tok = LocalTokens::internal_value();
///     assert_eq!(tok.as_str(), "internal_value");
/// }
///
/// use_tokens();
/// ```
#[macro_export]
macro_rules! define_private_tokens {
    (
        $name:ident {
            $($token:ident $(=> $str:literal)?),* $(,)?
        }
    ) => {
        $crate::define_tokens! {
            $name {
                $($token $(=> $str)?),*
            }
        }
    };
}

#[cfg(test)]
mod tests {
    use super::*;

    define_tokens! {
        /// Test tokens
        pub TestTokens {
            alpha,
            beta,
            gamma,
            custom_name => "customString",
        }
    }

    define_tokens! {
        /// Private test tokens (without pub)
        PrivateTokens {
            private_one,
            private_two,
        }
    }

    #[test]
    fn test_basic_tokens() {
        let alpha = TestTokens::alpha();
        let beta = TestTokens::beta();
        let gamma = TestTokens::gamma();

        assert_eq!(alpha.as_str(), "alpha");
        assert_eq!(beta.as_str(), "beta");
        assert_eq!(gamma.as_str(), "gamma");
    }

    #[test]
    fn test_custom_string() {
        let custom = TestTokens::custom_name();
        assert_eq!(custom.as_str(), "customString");
    }

    #[test]
    fn test_token_equality() {
        // Same token accessed multiple times should be equal
        let alpha1 = TestTokens::alpha();
        let alpha2 = TestTokens::alpha();
        assert_eq!(alpha1, alpha2);

        // Token should equal one created directly
        let alpha3 = Token::new("alpha");
        assert_eq!(alpha1, alpha3);
    }

    #[test]
    fn test_all_tokens() {
        let all = TestTokens::all_tokens();
        assert_eq!(all.len(), 4);

        assert!(all.contains(&TestTokens::alpha()));
        assert!(all.contains(&TestTokens::beta()));
        assert!(all.contains(&TestTokens::gamma()));
        assert!(all.contains(&TestTokens::custom_name()));
    }

    #[test]
    fn test_count() {
        assert_eq!(TestTokens::count(), 4);
        assert_eq!(PrivateTokens::count(), 2);
    }

    #[test]
    fn test_private_tokens() {
        let one = PrivateTokens::private_one();
        let two = PrivateTokens::private_two();

        assert_eq!(one.as_str(), "private_one");
        assert_eq!(two.as_str(), "private_two");
    }

    #[test]
    fn test_static_tokens_trait() {
        fn uses_trait<T: StaticTokens>() -> usize {
            T::all_tokens().len()
        }

        assert_eq!(uses_trait::<TestTokens>(), 4);
    }

    define_tokens! {
        /// Empty token group
        EmptyTokens {}
    }

    #[test]
    fn test_empty_tokens() {
        assert_eq!(EmptyTokens::all_tokens().len(), 0);
        assert_eq!(EmptyTokens::count(), 0);
    }

    define_tokens! {
        /// Single token
        SingleToken {
            only_one,
        }
    }

    #[test]
    fn test_single_token() {
        assert_eq!(SingleToken::count(), 1);
        assert_eq!(SingleToken::only_one().as_str(), "only_one");
    }

    #[test]
    fn test_tokens_are_interned() {
        // Tokens from static tokens should be the same object as
        // tokens created elsewhere with the same string
        let static_alpha = TestTokens::alpha();
        let manual_alpha = Token::new("alpha");

        // They should have the same internal pointer (both interned)
        assert_eq!(static_alpha, manual_alpha);
    }
}
