//! pxr.Vt — Value Types bindings.
//!
//! Implements drop-in replacement for `pxr.Vt` from C++ OpenUSD:
//! - `Value` / `_ValueWrapper` — type-erased value container with explicit factory methods
//! - `VtArray<T>` — 30+ typed array classes generated by macro
//! - `Dictionary` — bidirectional Python dict ↔ VtDictionary conversion

use pyo3::exceptions::{PyIndexError, PyTypeError, PyValueError};
use pyo3::prelude::*;
use pyo3::types::{PyDict, PyList, PySlice};

use usd_vt::{Array, Dictionary, Value};

// ============================================================================
// Helpers
// ============================================================================

/// Normalise a Python signed index into [0, len), returning IndexError on OOB.
fn norm_idx(i: isize, len: usize) -> PyResult<usize> {
    let len_i = len as isize;
    let idx = if i < 0 { len_i + i } else { i };
    if idx < 0 || idx >= len_i {
        Err(PyIndexError::new_err(format!(
            "index {i} out of range for array of length {len}"
        )))
    } else {
        Ok(idx as usize)
    }
}

/// Iterate a slice range according to PySliceIndices, collecting element indices.
fn slice_indices(step: isize, start: isize, stop: isize) -> Vec<usize> {
    let mut result = Vec::new();
    let mut idx = start;
    loop {
        if step > 0 && idx >= stop { break; }
        if step < 0 && idx <= stop { break; }
        if step == 0 { break; }
        result.push(idx as usize);
        idx += step;
    }
    result
}

// ============================================================================
// VtValue / _ValueWrapper
// ============================================================================

/// Explicit typed wrapper over `Value` — mirrors C++ `Vt._ValueWrapper`.
#[pyclass(name = "_ValueWrapper", module = "pxr.Vt")]
#[derive(Clone)]
pub struct PyValue {
    inner: Value,
    tag: &'static str,
}

#[pymethods]
impl PyValue {
    /// Auto-convert Python object to Value.
    #[new]
    #[pyo3(signature = (obj = None))]
    fn new(obj: Option<&Bound<'_, PyAny>>) -> PyResult<Self> {
        let Some(obj) = obj else {
            return Ok(Self { inner: Value::empty(), tag: "empty" });
        };
        // bool before int — Python bool is a subclass of int
        if let Ok(b) = obj.extract::<bool>() {
            return Ok(Self { inner: Value::new(b), tag: "bool" });
        }
        if let Ok(i) = obj.extract::<i64>() {
            if i >= i64::from(i32::MIN) && i <= i64::from(i32::MAX) {
                return Ok(Self { inner: Value::new(i as i32), tag: "int" });
            }
            return Ok(Self { inner: Value::new(i), tag: "int64" });
        }
        if let Ok(f) = obj.extract::<f64>() {
            return Ok(Self { inner: Value::from_f64(f), tag: "double" });
        }
        if let Ok(s) = obj.extract::<String>() {
            return Ok(Self { inner: Value::new(s), tag: "string" });
        }
        Ok(Self { inner: Value::empty(), tag: "unknown" })
    }

    #[staticmethod]
    #[pyo3(name = "Bool")]
    fn mk_bool(v: bool) -> Self { Self { inner: Value::new(v), tag: "bool" } }

    #[staticmethod]
    #[pyo3(name = "UChar")]
    fn mk_uchar(v: u8) -> Self { Self { inner: Value::new(v), tag: "uchar" } }

    #[staticmethod]
    #[pyo3(name = "Short")]
    fn mk_short(v: i16) -> Self { Self { inner: Value::new(v), tag: "short" } }

    #[staticmethod]
    #[pyo3(name = "UShort")]
    fn mk_ushort(v: u16) -> Self { Self { inner: Value::new(v), tag: "ushort" } }

    #[staticmethod]
    #[pyo3(name = "Int")]
    fn mk_int(v: i32) -> Self { Self { inner: Value::new(v), tag: "int" } }

    #[staticmethod]
    #[pyo3(name = "UInt")]
    fn mk_uint(v: u32) -> Self { Self { inner: Value::new(v), tag: "uint" } }

    #[staticmethod]
    #[pyo3(name = "Long")]
    fn mk_long(v: i64) -> Self { Self { inner: Value::new(v), tag: "long" } }

    #[staticmethod]
    #[pyo3(name = "Int64")]
    fn mk_int64(v: i64) -> Self { Self { inner: Value::new(v), tag: "int64" } }

    #[staticmethod]
    #[pyo3(name = "ULong")]
    fn mk_ulong(v: u64) -> Self { Self { inner: Value::new(v), tag: "ulong" } }

    #[staticmethod]
    #[pyo3(name = "UInt64")]
    fn mk_uint64(v: u64) -> Self { Self { inner: Value::new(v), tag: "uint64" } }

    #[staticmethod]
    #[pyo3(name = "Float")]
    fn mk_float(v: f32) -> Self { Self { inner: Value::from_f32(v), tag: "float" } }

    #[staticmethod]
    #[pyo3(name = "Double")]
    fn mk_double(v: f64) -> Self { Self { inner: Value::from_f64(v), tag: "double" } }

    /// Half stored as f32 proxy — Python has no native f16 type.
    #[staticmethod]
    #[pyo3(name = "Half")]
    fn mk_half(v: f32) -> Self { Self { inner: Value::from_f32(v), tag: "half" } }

    #[staticmethod]
    #[pyo3(name = "Token")]
    fn mk_token(v: &str) -> Self {
        Self { inner: Value::new(usd_tf::Token::new(v)), tag: "token" }
    }

    #[pyo3(name = "IsEmpty")]
    fn is_empty(&self) -> bool { self.inner.is_empty() }

    fn __eq__(&self, other: &Self) -> bool { self.inner == other.inner }
    fn __ne__(&self, other: &Self) -> bool { self.inner != other.inner }

    fn __str__(&self) -> String { format_value(&self.inner) }

    fn __repr__(&self) -> String {
        format!("Vt._ValueWrapper({}: {})", self.tag, format_value(&self.inner))
    }
}

fn format_value(v: &Value) -> String {
    if v.is_empty() { return "<empty>".to_owned(); }
    if let Some(b) = v.get::<bool>()   { return format!("{b}"); }
    if let Some(i) = v.get::<i32>()    { return format!("{i}"); }
    if let Some(i) = v.get::<i64>()    { return format!("{i}"); }
    if let Some(u) = v.get::<u64>()    { return format!("{u}"); }
    if let Some(x) = v.get::<f64>()    { return format!("{x}"); }
    if let Some(x) = v.get::<f32>()    { return format!("{x}"); }
    if let Some(s) = v.get::<String>() { return s.clone(); }
    if let Some(t) = v.get::<usd_tf::Token>() { return t.to_string(); }
    "<value>".to_owned()
}

// ============================================================================
// Concrete scalar iterators — one struct per type (PyO3 forbids generics)
// ============================================================================

macro_rules! define_scalar_iter {
    ($name:ident, $elem:ty) => {
        #[pyclass]
        pub struct $name { data: Vec<$elem>, pos: usize }

        impl $name {
            pub fn new_from_data(data: Vec<$elem>) -> Self { Self { data, pos: 0 } }
        }

        #[pymethods]
        impl $name {
            fn __iter__(slf: PyRef<'_, Self>) -> PyRef<'_, Self> { slf }
            fn __next__(mut slf: PyRefMut<'_, Self>) -> Option<$elem> {
                if slf.pos < slf.data.len() {
                    let v = slf.data[slf.pos];
                    slf.pos += 1;
                    Some(v)
                } else { None }
            }
        }
    };
}

define_scalar_iter!(VtBoolIter, bool);
define_scalar_iter!(VtI8Iter,   i8);
define_scalar_iter!(VtU8Iter,   u8);
define_scalar_iter!(VtI16Iter,  i16);
define_scalar_iter!(VtU16Iter,  u16);
define_scalar_iter!(VtI32Iter,  i32);
define_scalar_iter!(VtU32Iter,  u32);
define_scalar_iter!(VtI64Iter,  i64);
define_scalar_iter!(VtU64Iter,  u64);
define_scalar_iter!(VtF32Iter,  f32);
define_scalar_iter!(VtF64Iter,  f64);

/// String-based iterator for Token, vec, matrix arrays.
#[pyclass]
pub struct VtStringIter { data: Vec<String>, pos: usize }

impl VtStringIter {
    pub fn new_from_data(data: Vec<String>) -> Self { Self { data, pos: 0 } }
}

#[pymethods]
impl VtStringIter {
    fn __iter__(slf: PyRef<'_, Self>) -> PyRef<'_, Self> { slf }
    fn __next__(mut slf: PyRefMut<'_, Self>) -> Option<String> {
        if slf.pos < slf.data.len() {
            let s = slf.data[slf.pos].clone();
            slf.pos += 1;
            Some(s)
        } else { None }
    }
}

// ============================================================================
// Generic array construction helpers
// ============================================================================

/// Build `Array<T>` from None (empty), usize (fill with default), or sequence.
fn build_array<T>(arg: Option<&Bound<'_, PyAny>>, default: fn() -> T) -> PyResult<Array<T>>
where
    T: Clone + Send + Sync + for<'py> FromPyObject<'py> + 'static,
{
    let Some(obj) = arg else { return Ok(Array::new()); };
    if let Ok(n) = obj.extract::<usize>() {
        return Ok(Array::from_elem(default(), n));
    }
    let list: Vec<T> = obj.extract()
        .map_err(|_| PyValueError::new_err("expected int size or sequence"))?;
    Ok(Array::from(list))
}

/// Same as `build_array` for types with Default.
fn build_array_clone<T>(arg: Option<&Bound<'_, PyAny>>) -> PyResult<Array<T>>
where
    T: Clone + Send + Sync + Default + for<'py> FromPyObject<'py> + 'static,
{
    let Some(obj) = arg else { return Ok(Array::new()); };
    if let Ok(n) = obj.extract::<usize>() {
        return Ok(Array::from_elem(T::default(), n));
    }
    let list: Vec<T> = obj.extract()
        .map_err(|_| PyValueError::new_err("expected int size or sequence"))?;
    Ok(Array::from(list))
}

/// Build `Array<T>` mapping from Python elements of type `PyElem`.
fn build_array_mapped<T, PyElem>(
    arg: Option<&Bound<'_, PyAny>>,
    from_py: fn(PyElem) -> T,
) -> PyResult<Array<T>>
where
    T: Clone + Send + Sync + Default + 'static,
    PyElem: for<'py> FromPyObject<'py>,
{
    let Some(obj) = arg else { return Ok(Array::new()); };
    if let Ok(n) = obj.extract::<usize>() {
        return Ok(Array::from_elem(T::default(), n));
    }
    let list: Vec<PyElem> = obj.extract()
        .map_err(|_| PyValueError::new_err("expected int size or sequence"))?;
    Ok(Array::from(list.into_iter().map(from_py).collect::<Vec<_>>()))
}

// ============================================================================
// VtArray macro
// ============================================================================
//
// Three arms:
//   `numeric_signed`  — signed scalars: full arith including neg
//   `numeric_unsigned` — unsigned scalars: add/sub/mul/div but no neg
//   `no_arith`        — bool, no arithmetic
//   `string_like`     — String/Token: only add (concatenate)
//   `vec_like`        — Gf vec/matrix: comparison + str, no arithmetic

macro_rules! vt_array {
    // ---- signed numeric scalars ----
    (
        numeric_signed,
        name    = $py_name:literal,
        module  = $py_mod:literal,
        rust    = $rust_name:ident,
        elem    = $elem:ty,
        iter_ty = $iter_ty:ident
    ) => {
        #[pyclass(name = $py_name, module = $py_mod)]
        #[derive(Clone)]
        pub struct $rust_name { inner: Array<$elem> }

        #[pymethods]
        impl $rust_name {
            #[new]
            #[pyo3(signature = (arg = None))]
            fn new(arg: Option<&Bound<'_, PyAny>>) -> PyResult<Self> {
                build_array::<$elem>(arg, Default::default).map(|inner| Self { inner })
            }

            fn __len__(&self) -> usize { self.inner.len() }

            fn __getitem__(&self, py: Python<'_>, key: &Bound<'_, PyAny>) -> PyResult<PyObject> {
                if let Ok(i) = key.extract::<isize>() {
                    let idx = norm_idx(i, self.inner.len())?;
                    Ok(self.inner.as_slice()[idx].into_py(py))
                } else if let Ok(slice) = key.downcast::<PySlice>() {
                    let raw = slice.indices(self.inner.len() as _)?;
                    let indices = slice_indices(raw.step as isize, raw.start as isize, raw.stop as isize);
                    let list = PyList::empty(py);
                    for i in indices { list.append(self.inner.as_slice()[i].into_py(py))?; }
                    Ok(list.into())
                } else {
                    Err(PyTypeError::new_err("index must be int or slice"))
                }
            }

            fn __setitem__(&mut self, key: &Bound<'_, PyAny>, value: &Bound<'_, PyAny>) -> PyResult<()> {
                if let Ok(i) = key.extract::<isize>() {
                    let idx = norm_idx(i, self.inner.len())?;
                    let elem: $elem = value.extract()?;
                    self.inner.make_unique();
                    self.inner.as_mut_slice()
                        .ok_or_else(|| PyValueError::new_err("array is not uniquely owned"))?[idx] = elem;
                    Ok(())
                } else if let Ok(slice) = key.downcast::<PySlice>() {
                    let raw = slice.indices(self.inner.len() as _)?;
                    let indices = slice_indices(raw.step as isize, raw.start as isize, raw.stop as isize);
                    let elems: Vec<$elem> = value.extract()?;
                    self.inner.make_unique();
                    let data = self.inner.as_mut_slice()
                        .ok_or_else(|| PyValueError::new_err("array is not uniquely owned"))?;
                    for (i, elem) in indices.into_iter().zip(elems) { data[i] = elem; }
                    Ok(())
                } else {
                    Err(PyTypeError::new_err("index must be int or slice"))
                }
            }

            fn __iter__(slf: PyRef<'_, Self>) -> PyResult<Py<$iter_ty>> {
                Py::new(slf.py(), $iter_ty::new_from_data(slf.inner.as_slice().to_vec()))
            }

            fn __eq__(&self, other: &Self) -> bool { self.inner.as_slice() == other.inner.as_slice() }
            fn __ne__(&self, other: &Self) -> bool { self.inner.as_slice() != other.inner.as_slice() }

            fn __repr__(&self) -> String {
                let elems: Vec<String> = self.inner.as_slice().iter().map(|x| format!("{x}")).collect();
                format!("Vt.{}([{}])", $py_name, elems.join(", "))
            }
            fn __str__(&self) -> String {
                let elems: Vec<String> = self.inner.as_slice().iter().map(|x| format!("{x}")).collect();
                format!("[{}]", elems.join(", "))
            }

            fn __add__(&self, other: &Self) -> Self {
                Self { inner: Array::from(self.inner.as_slice().iter().zip(other.inner.as_slice()).map(|(a, b)| *a + *b).collect::<Vec<_>>()) }
            }
            fn __radd__(&self, other: &Self) -> Self { self.__add__(other) }
            fn __sub__(&self, other: &Self) -> Self {
                Self { inner: Array::from(self.inner.as_slice().iter().zip(other.inner.as_slice()).map(|(a, b)| *a - *b).collect::<Vec<_>>()) }
            }
            fn __rsub__(&self, other: &Self) -> Self { other.__sub__(self) }
            fn __neg__(&self) -> Self {
                Self { inner: Array::from(self.inner.as_slice().iter().map(|a| -(*a)).collect::<Vec<_>>()) }
            }
            fn __mul__(&self, scalar: f64) -> Self {
                let s = scalar as $elem;
                Self { inner: Array::from(self.inner.as_slice().iter().map(|a| *a * s).collect::<Vec<_>>()) }
            }
            fn __rmul__(&self, scalar: f64) -> Self { self.__mul__(scalar) }
            fn __truediv__(&self, scalar: f64) -> PyResult<Self> {
                if scalar == 0.0 {
                    return Err(pyo3::exceptions::PyZeroDivisionError::new_err("division by zero"));
                }
                let s = scalar as $elem;
                Ok(Self { inner: Array::from(self.inner.as_slice().iter().map(|a| *a / s).collect::<Vec<_>>()) })
            }
        }
    };

    // ---- unsigned numeric scalars (no neg) ----
    (
        numeric_unsigned,
        name    = $py_name:literal,
        module  = $py_mod:literal,
        rust    = $rust_name:ident,
        elem    = $elem:ty,
        iter_ty = $iter_ty:ident
    ) => {
        #[pyclass(name = $py_name, module = $py_mod)]
        #[derive(Clone)]
        pub struct $rust_name { inner: Array<$elem> }

        #[pymethods]
        impl $rust_name {
            #[new]
            #[pyo3(signature = (arg = None))]
            fn new(arg: Option<&Bound<'_, PyAny>>) -> PyResult<Self> {
                build_array::<$elem>(arg, Default::default).map(|inner| Self { inner })
            }

            fn __len__(&self) -> usize { self.inner.len() }

            fn __getitem__(&self, py: Python<'_>, key: &Bound<'_, PyAny>) -> PyResult<PyObject> {
                if let Ok(i) = key.extract::<isize>() {
                    let idx = norm_idx(i, self.inner.len())?;
                    Ok(self.inner.as_slice()[idx].into_py(py))
                } else if let Ok(slice) = key.downcast::<PySlice>() {
                    let raw = slice.indices(self.inner.len() as _)?;
                    let indices = slice_indices(raw.step as isize, raw.start as isize, raw.stop as isize);
                    let list = PyList::empty(py);
                    for i in indices { list.append(self.inner.as_slice()[i].into_py(py))?; }
                    Ok(list.into())
                } else {
                    Err(PyTypeError::new_err("index must be int or slice"))
                }
            }

            fn __setitem__(&mut self, key: &Bound<'_, PyAny>, value: &Bound<'_, PyAny>) -> PyResult<()> {
                if let Ok(i) = key.extract::<isize>() {
                    let idx = norm_idx(i, self.inner.len())?;
                    let elem: $elem = value.extract()?;
                    self.inner.make_unique();
                    self.inner.as_mut_slice()
                        .ok_or_else(|| PyValueError::new_err("array is not uniquely owned"))?[idx] = elem;
                    Ok(())
                } else {
                    Err(PyTypeError::new_err("index must be int"))
                }
            }

            fn __iter__(slf: PyRef<'_, Self>) -> PyResult<Py<$iter_ty>> {
                Py::new(slf.py(), $iter_ty::new_from_data(slf.inner.as_slice().to_vec()))
            }

            fn __eq__(&self, other: &Self) -> bool { self.inner.as_slice() == other.inner.as_slice() }
            fn __ne__(&self, other: &Self) -> bool { self.inner.as_slice() != other.inner.as_slice() }

            fn __repr__(&self) -> String {
                let elems: Vec<String> = self.inner.as_slice().iter().map(|x| format!("{x}")).collect();
                format!("Vt.{}([{}])", $py_name, elems.join(", "))
            }
            fn __str__(&self) -> String {
                let elems: Vec<String> = self.inner.as_slice().iter().map(|x| format!("{x}")).collect();
                format!("[{}]", elems.join(", "))
            }

            fn __add__(&self, other: &Self) -> Self {
                Self { inner: Array::from(self.inner.as_slice().iter().zip(other.inner.as_slice()).map(|(a, b)| *a + *b).collect::<Vec<_>>()) }
            }
            fn __radd__(&self, other: &Self) -> Self { self.__add__(other) }
            fn __sub__(&self, other: &Self) -> Self {
                Self { inner: Array::from(self.inner.as_slice().iter().zip(other.inner.as_slice()).map(|(a, b)| *a - *b).collect::<Vec<_>>()) }
            }
            fn __rsub__(&self, other: &Self) -> Self { other.__sub__(self) }
            fn __mul__(&self, scalar: f64) -> Self {
                let s = scalar as $elem;
                Self { inner: Array::from(self.inner.as_slice().iter().map(|a| *a * s).collect::<Vec<_>>()) }
            }
            fn __rmul__(&self, scalar: f64) -> Self { self.__mul__(scalar) }
            fn __truediv__(&self, scalar: f64) -> PyResult<Self> {
                if scalar == 0.0 {
                    return Err(pyo3::exceptions::PyZeroDivisionError::new_err("division by zero"));
                }
                let s = scalar as $elem;
                Ok(Self { inner: Array::from(self.inner.as_slice().iter().map(|a| *a / s).collect::<Vec<_>>()) })
            }
        }
    };

    // ---- no-arithmetic (bool, etc.) ----
    (
        no_arith,
        name    = $py_name:literal,
        module  = $py_mod:literal,
        rust    = $rust_name:ident,
        elem    = $elem:ty,
        iter_ty = $iter_ty:ident
    ) => {
        #[pyclass(name = $py_name, module = $py_mod)]
        #[derive(Clone)]
        pub struct $rust_name { inner: Array<$elem> }

        #[pymethods]
        impl $rust_name {
            #[new]
            #[pyo3(signature = (arg = None))]
            fn new(arg: Option<&Bound<'_, PyAny>>) -> PyResult<Self> {
                build_array::<$elem>(arg, Default::default).map(|inner| Self { inner })
            }

            fn __len__(&self) -> usize { self.inner.len() }

            fn __getitem__(&self, py: Python<'_>, key: &Bound<'_, PyAny>) -> PyResult<PyObject> {
                if let Ok(i) = key.extract::<isize>() {
                    let idx = norm_idx(i, self.inner.len())?;
                    Ok(self.inner.as_slice()[idx].into_py(py))
                } else if let Ok(slice) = key.downcast::<PySlice>() {
                    let raw = slice.indices(self.inner.len() as _)?;
                    let indices = slice_indices(raw.step as isize, raw.start as isize, raw.stop as isize);
                    let list = PyList::empty(py);
                    for i in indices { list.append(self.inner.as_slice()[i].into_py(py))?; }
                    Ok(list.into())
                } else {
                    Err(PyTypeError::new_err("index must be int or slice"))
                }
            }

            fn __setitem__(&mut self, key: &Bound<'_, PyAny>, value: &Bound<'_, PyAny>) -> PyResult<()> {
                if let Ok(i) = key.extract::<isize>() {
                    let idx = norm_idx(i, self.inner.len())?;
                    let elem: $elem = value.extract()?;
                    self.inner.make_unique();
                    self.inner.as_mut_slice()
                        .ok_or_else(|| PyValueError::new_err("array is not uniquely owned"))?[idx] = elem;
                    Ok(())
                } else {
                    Err(PyTypeError::new_err("index must be int"))
                }
            }

            fn __iter__(slf: PyRef<'_, Self>) -> PyResult<Py<$iter_ty>> {
                Py::new(slf.py(), $iter_ty::new_from_data(slf.inner.as_slice().to_vec()))
            }

            fn __eq__(&self, other: &Self) -> bool { self.inner.as_slice() == other.inner.as_slice() }
            fn __ne__(&self, other: &Self) -> bool { self.inner.as_slice() != other.inner.as_slice() }

            fn __repr__(&self) -> String {
                let elems: Vec<String> = self.inner.as_slice().iter().map(|x| format!("{x}")).collect();
                format!("Vt.{}([{}])", $py_name, elems.join(", "))
            }
            fn __str__(&self) -> String {
                let elems: Vec<String> = self.inner.as_slice().iter().map(|x| format!("{x}")).collect();
                format!("[{}]", elems.join(", "))
            }
        }
    };

    // ---- string-like (String, Token) — add only ----
    (
        string_like,
        name   = $py_name:literal,
        module = $py_mod:literal,
        rust   = $rust_name:ident,
        elem   = $elem:ty
    ) => {
        #[pyclass(name = $py_name, module = $py_mod)]
        #[derive(Clone)]
        pub struct $rust_name { inner: Array<$elem> }

        #[pymethods]
        impl $rust_name {
            #[new]
            #[pyo3(signature = (arg = None))]
            fn new(arg: Option<&Bound<'_, PyAny>>) -> PyResult<Self> {
                build_array_clone::<$elem>(arg).map(|inner| Self { inner })
            }

            fn __len__(&self) -> usize { self.inner.len() }

            fn __getitem__(&self, py: Python<'_>, key: &Bound<'_, PyAny>) -> PyResult<PyObject> {
                if let Ok(i) = key.extract::<isize>() {
                    let idx = norm_idx(i, self.inner.len())?;
                    Ok(self.inner.as_slice()[idx].clone().into_py(py))
                } else if let Ok(slice) = key.downcast::<PySlice>() {
                    let raw = slice.indices(self.inner.len() as _)?;
                    let indices = slice_indices(raw.step as isize, raw.start as isize, raw.stop as isize);
                    let list = PyList::empty(py);
                    for i in indices { list.append(self.inner.as_slice()[i].clone().into_py(py))?; }
                    Ok(list.into())
                } else {
                    Err(PyTypeError::new_err("index must be int or slice"))
                }
            }

            fn __setitem__(&mut self, key: &Bound<'_, PyAny>, value: &Bound<'_, PyAny>) -> PyResult<()> {
                if let Ok(i) = key.extract::<isize>() {
                    let idx = norm_idx(i, self.inner.len())?;
                    let elem: $elem = value.extract()?;
                    self.inner.make_unique();
                    self.inner.as_mut_slice()
                        .ok_or_else(|| PyValueError::new_err("array is not uniquely owned"))?[idx] = elem;
                    Ok(())
                } else {
                    Err(PyTypeError::new_err("index must be int"))
                }
            }

            fn __iter__(slf: PyRef<'_, Self>) -> PyResult<Py<VtStringIter>> {
                let data = slf.inner.as_slice().iter().map(|s| format!("{s}")).collect();
                Py::new(slf.py(), VtStringIter::new_from_data(data))
            }

            fn __eq__(&self, other: &Self) -> bool { self.inner.as_slice() == other.inner.as_slice() }
            fn __ne__(&self, other: &Self) -> bool { self.inner.as_slice() != other.inner.as_slice() }

            fn __repr__(&self) -> String {
                let elems: Vec<String> = self.inner.as_slice().iter().map(|s| format!("{s:?}")).collect();
                format!("Vt.{}([{}])", $py_name, elems.join(", "))
            }
            fn __str__(&self) -> String {
                let elems: Vec<String> = self.inner.as_slice().iter().map(|s| format!("{s}")).collect();
                format!("[{}]", elems.join(", "))
            }

            fn __add__(&self, other: &Self) -> Self {
                let mut data = self.inner.as_slice().to_vec();
                data.extend_from_slice(other.inner.as_slice());
                Self { inner: Array::from(data) }
            }
        }
    };

    // ---- vec-like (usd_gf::Vec*, mapped from/to Python tuples) ----
    (
        vec_like,
        name    = $py_name:literal,
        module  = $py_mod:literal,
        rust    = $rust_name:ident,
        elem    = $elem:ty,
        py_elem = $py_elem:ty,
        from_py = $from_py:expr,
        to_py   = $to_py:expr
    ) => {
        #[pyclass(name = $py_name, module = $py_mod)]
        #[derive(Clone)]
        pub struct $rust_name { inner: Array<$elem> }

        #[pymethods]
        impl $rust_name {
            #[new]
            #[pyo3(signature = (arg = None))]
            fn new(arg: Option<&Bound<'_, PyAny>>) -> PyResult<Self> {
                build_array_mapped::<$elem, $py_elem>(arg, $from_py).map(|inner| Self { inner })
            }

            fn __len__(&self) -> usize { self.inner.len() }

            fn __getitem__(&self, py: Python<'_>, key: &Bound<'_, PyAny>) -> PyResult<PyObject> {
                if let Ok(i) = key.extract::<isize>() {
                    let idx = norm_idx(i, self.inner.len())?;
                    Ok(($to_py)(self.inner.as_slice()[idx].clone()).into_py(py))
                } else if let Ok(slice) = key.downcast::<PySlice>() {
                    let raw = slice.indices(self.inner.len() as _)?;
                    let indices = slice_indices(raw.step as isize, raw.start as isize, raw.stop as isize);
                    let list = PyList::empty(py);
                    for i in indices {
                        list.append(($to_py)(self.inner.as_slice()[i].clone()).into_py(py))?;
                    }
                    Ok(list.into())
                } else {
                    Err(PyTypeError::new_err("index must be int or slice"))
                }
            }

            fn __setitem__(&mut self, key: &Bound<'_, PyAny>, value: &Bound<'_, PyAny>) -> PyResult<()> {
                if let Ok(i) = key.extract::<isize>() {
                    let idx = norm_idx(i, self.inner.len())?;
                    let py_val: $py_elem = value.extract()?;
                    self.inner.make_unique();
                    self.inner.as_mut_slice()
                        .ok_or_else(|| PyValueError::new_err("array is not uniquely owned"))?[idx] = ($from_py)(py_val);
                    Ok(())
                } else {
                    Err(PyTypeError::new_err("index must be int"))
                }
            }

            fn __iter__(slf: PyRef<'_, Self>) -> PyResult<Py<VtStringIter>> {
                let data = slf.inner.as_slice().iter()
                    .map(|v| format!("{:?}", ($to_py)(v.clone())))
                    .collect();
                Py::new(slf.py(), VtStringIter::new_from_data(data))
            }

            fn __eq__(&self, other: &Self) -> bool { self.inner.as_slice() == other.inner.as_slice() }
            fn __ne__(&self, other: &Self) -> bool { self.inner.as_slice() != other.inner.as_slice() }

            fn __repr__(&self) -> String {
                let elems: Vec<String> = self.inner.as_slice().iter()
                    .map(|v| format!("{:?}", ($to_py)(v.clone()))).collect();
                format!("Vt.{}([{}])", $py_name, elems.join(", "))
            }
            fn __str__(&self) -> String {
                let elems: Vec<String> = self.inner.as_slice().iter()
                    .map(|v| format!("{:?}", ($to_py)(v.clone()))).collect();
                format!("[{}]", elems.join(", "))
            }
        }
    };
}

// ============================================================================
// Scalar array instantiations
// ============================================================================

vt_array!(no_arith,
    name = "BoolArray", module = "pxr.Vt",
    rust = PyBoolArray, elem = bool,
    iter_ty = VtBoolIter
);

vt_array!(numeric_unsigned,
    name = "UCharArray", module = "pxr.Vt",
    rust = PyUCharArray, elem = u8,
    iter_ty = VtU8Iter
);

vt_array!(numeric_signed,
    name = "ShortArray", module = "pxr.Vt",
    rust = PyShortArray, elem = i16,
    iter_ty = VtI16Iter
);

vt_array!(numeric_unsigned,
    name = "UShortArray", module = "pxr.Vt",
    rust = PyUShortArray, elem = u16,
    iter_ty = VtU16Iter
);

vt_array!(numeric_signed,
    name = "IntArray", module = "pxr.Vt",
    rust = PyIntArray, elem = i32,
    iter_ty = VtI32Iter
);

vt_array!(numeric_unsigned,
    name = "UIntArray", module = "pxr.Vt",
    rust = PyUIntArray, elem = u32,
    iter_ty = VtU32Iter
);

vt_array!(numeric_signed,
    name = "Int64Array", module = "pxr.Vt",
    rust = PyInt64Array, elem = i64,
    iter_ty = VtI64Iter
);

vt_array!(numeric_unsigned,
    name = "UInt64Array", module = "pxr.Vt",
    rust = PyUInt64Array, elem = u64,
    iter_ty = VtU64Iter
);

vt_array!(numeric_signed,
    name = "FloatArray", module = "pxr.Vt",
    rust = PyFloatArray, elem = f32,
    iter_ty = VtF32Iter
);

vt_array!(numeric_signed,
    name = "DoubleArray", module = "pxr.Vt",
    rust = PyDoubleArray, elem = f64,
    iter_ty = VtF64Iter
);

// Half stored as f32 — no native Python half type
vt_array!(numeric_signed,
    name = "HalfArray", module = "pxr.Vt",
    rust = PyHalfArray, elem = f32,
    iter_ty = VtF32Iter
);

// ============================================================================
// String / Token arrays
// ============================================================================

vt_array!(string_like,
    name = "StringArray", module = "pxr.Vt",
    rust = PyStringArray, elem = String
);

/// `TokenArray` — each token exposed to Python as a `str`.
#[pyclass(name = "TokenArray", module = "pxr.Vt")]
#[derive(Clone)]
pub struct PyTokenArray { inner: Array<usd_tf::Token> }

#[pymethods]
impl PyTokenArray {
    #[new]
    #[pyo3(signature = (arg = None))]
    fn new(arg: Option<&Bound<'_, PyAny>>) -> PyResult<Self> {
        let Some(obj) = arg else {
            return Ok(Self { inner: Array::new() });
        };
        if let Ok(n) = obj.extract::<usize>() {
            return Ok(Self { inner: Array::from_elem(usd_tf::Token::new(""), n) });
        }
        let strings: Vec<String> = obj.extract()
            .map_err(|_| PyValueError::new_err("expected int size or list of str"))?;
        Ok(Self { inner: Array::from(strings.iter().map(|s| usd_tf::Token::new(s)).collect::<Vec<_>>()) })
    }

    fn __len__(&self) -> usize { self.inner.len() }

    fn __getitem__(&self, py: Python<'_>, key: &Bound<'_, PyAny>) -> PyResult<PyObject> {
        if let Ok(i) = key.extract::<isize>() {
            let idx = norm_idx(i, self.inner.len())?;
            Ok(self.inner.as_slice()[idx].to_string().into_py(py))
        } else if let Ok(slice) = key.downcast::<PySlice>() {
            let raw = slice.indices(self.inner.len() as _)?;
            let indices = slice_indices(raw.step as isize, raw.start as isize, raw.stop as isize);
            let list = PyList::empty(py);
            for i in indices { list.append(self.inner.as_slice()[i].to_string().into_py(py))?; }
            Ok(list.into())
        } else {
            Err(PyTypeError::new_err("index must be int or slice"))
        }
    }

    fn __setitem__(&mut self, key: &Bound<'_, PyAny>, value: &Bound<'_, PyAny>) -> PyResult<()> {
        if let Ok(i) = key.extract::<isize>() {
            let idx = norm_idx(i, self.inner.len())?;
            let s: String = value.extract()?;
            self.inner.make_unique();
            self.inner.as_mut_slice()
                .ok_or_else(|| PyValueError::new_err("array is not uniquely owned"))?[idx]
                = usd_tf::Token::new(&s);
            Ok(())
        } else {
            Err(PyTypeError::new_err("index must be int"))
        }
    }

    fn __iter__(slf: PyRef<'_, Self>) -> PyResult<Py<VtStringIter>> {
        let data = slf.inner.as_slice().iter().map(|t| t.to_string()).collect();
        Py::new(slf.py(), VtStringIter::new_from_data(data))
    }

    fn __eq__(&self, other: &Self) -> bool { self.inner.as_slice() == other.inner.as_slice() }
    fn __ne__(&self, other: &Self) -> bool { self.inner.as_slice() != other.inner.as_slice() }

    fn __repr__(&self) -> String {
        let elems: Vec<String> = self.inner.as_slice().iter().map(|t| format!("{t:?}")).collect();
        format!("Vt.TokenArray([{}])", elems.join(", "))
    }
    fn __str__(&self) -> String {
        let elems: Vec<String> = self.inner.as_slice().iter().map(|t| t.to_string()).collect();
        format!("[{}]", elems.join(", "))
    }
}

// ============================================================================
// Vec2/3/4 f/d/i arrays
//
// Python element representation: tuple of scalars, e.g. (f32, f32, f32).
// Keeps Vt self-contained — avoids circular import with Gf module.
// ============================================================================

vt_array!(vec_like,
    name = "Vec2fArray", module = "pxr.Vt",
    rust = PyVec2fArray,
    elem = usd_gf::Vec2f, py_elem = (f32, f32),
    from_py = |(x, y): (f32, f32)| usd_gf::Vec2f::new(x, y),
    to_py   = |v: usd_gf::Vec2f| (v[0], v[1])
);

vt_array!(vec_like,
    name = "Vec3fArray", module = "pxr.Vt",
    rust = PyVec3fArray,
    elem = usd_gf::Vec3f, py_elem = (f32, f32, f32),
    from_py = |(x, y, z): (f32, f32, f32)| usd_gf::Vec3f::new(x, y, z),
    to_py   = |v: usd_gf::Vec3f| (v[0], v[1], v[2])
);

vt_array!(vec_like,
    name = "Vec4fArray", module = "pxr.Vt",
    rust = PyVec4fArray,
    elem = usd_gf::Vec4f, py_elem = (f32, f32, f32, f32),
    from_py = |(x, y, z, w): (f32, f32, f32, f32)| usd_gf::Vec4f::new(x, y, z, w),
    to_py   = |v: usd_gf::Vec4f| (v[0], v[1], v[2], v[3])
);

vt_array!(vec_like,
    name = "Vec2dArray", module = "pxr.Vt",
    rust = PyVec2dArray,
    elem = usd_gf::Vec2d, py_elem = (f64, f64),
    from_py = |(x, y): (f64, f64)| usd_gf::Vec2d::new(x, y),
    to_py   = |v: usd_gf::Vec2d| (v[0], v[1])
);

vt_array!(vec_like,
    name = "Vec3dArray", module = "pxr.Vt",
    rust = PyVec3dArray,
    elem = usd_gf::Vec3d, py_elem = (f64, f64, f64),
    from_py = |(x, y, z): (f64, f64, f64)| usd_gf::Vec3d::new(x, y, z),
    to_py   = |v: usd_gf::Vec3d| (v[0], v[1], v[2])
);

vt_array!(vec_like,
    name = "Vec4dArray", module = "pxr.Vt",
    rust = PyVec4dArray,
    elem = usd_gf::Vec4d, py_elem = (f64, f64, f64, f64),
    from_py = |(x, y, z, w): (f64, f64, f64, f64)| usd_gf::Vec4d::new(x, y, z, w),
    to_py   = |v: usd_gf::Vec4d| (v[0], v[1], v[2], v[3])
);

vt_array!(vec_like,
    name = "Vec2iArray", module = "pxr.Vt",
    rust = PyVec2iArray,
    elem = usd_gf::Vec2i, py_elem = (i32, i32),
    from_py = |(x, y): (i32, i32)| usd_gf::Vec2i::new(x, y),
    to_py   = |v: usd_gf::Vec2i| (v[0], v[1])
);

vt_array!(vec_like,
    name = "Vec3iArray", module = "pxr.Vt",
    rust = PyVec3iArray,
    elem = usd_gf::Vec3i, py_elem = (i32, i32, i32),
    from_py = |(x, y, z): (i32, i32, i32)| usd_gf::Vec3i::new(x, y, z),
    to_py   = |v: usd_gf::Vec3i| (v[0], v[1], v[2])
);

vt_array!(vec_like,
    name = "Vec4iArray", module = "pxr.Vt",
    rust = PyVec4iArray,
    elem = usd_gf::Vec4i, py_elem = (i32, i32, i32, i32),
    from_py = |(x, y, z, w): (i32, i32, i32, i32)| usd_gf::Vec4i::new(x, y, z, w),
    to_py   = |v: usd_gf::Vec4i| (v[0], v[1], v[2], v[3])
);

// ============================================================================
// Matrix4 arrays — flat Vec<f64/f32> (16 elements, row-major)
// ============================================================================

/// Flatten Matrix4d to 16-element Vec<f64> (row-major).
fn mat4d_to_flat(m: &usd_gf::Matrix4d) -> Vec<f64> {
    let a = m.to_array();
    a.iter().flat_map(|row| row.iter().copied()).collect()
}

fn flat_to_mat4d(flat: &[f64]) -> Option<usd_gf::Matrix4d> {
    if flat.len() != 16 { return None; }
    Some(usd_gf::Matrix4d::from_array([
        [flat[0],  flat[1],  flat[2],  flat[3]],
        [flat[4],  flat[5],  flat[6],  flat[7]],
        [flat[8],  flat[9],  flat[10], flat[11]],
        [flat[12], flat[13], flat[14], flat[15]],
    ]))
}

fn mat4f_to_flat(m: &usd_gf::Matrix4f) -> Vec<f32> {
    let a = m.to_array();
    a.iter().flat_map(|row| row.iter().copied()).collect()
}

fn flat_to_mat4f(flat: &[f32]) -> Option<usd_gf::Matrix4f> {
    if flat.len() != 16 { return None; }
    Some(usd_gf::Matrix4f::from_array([
        [flat[0],  flat[1],  flat[2],  flat[3]],
        [flat[4],  flat[5],  flat[6],  flat[7]],
        [flat[8],  flat[9],  flat[10], flat[11]],
        [flat[12], flat[13], flat[14], flat[15]],
    ]))
}

#[pyclass(name = "Matrix4dArray", module = "pxr.Vt")]
#[derive(Clone)]
pub struct PyMatrix4dArray { inner: Array<usd_gf::Matrix4d> }

#[pymethods]
impl PyMatrix4dArray {
    /// `Matrix4dArray()`, `Matrix4dArray(n)`, or `Matrix4dArray([[f64;16], ...])`.
    #[new]
    #[pyo3(signature = (arg = None))]
    fn new(arg: Option<&Bound<'_, PyAny>>) -> PyResult<Self> {
        let Some(obj) = arg else {
            return Ok(Self { inner: Array::new() });
        };
        if let Ok(n) = obj.extract::<usize>() {
            return Ok(Self { inner: Array::from_elem(usd_gf::Matrix4d::identity(), n) });
        }
        let items: Vec<Vec<f64>> = obj.extract()
            .map_err(|_| PyValueError::new_err("expected int or list of 16-float lists"))?;
        let mats: Vec<usd_gf::Matrix4d> = items.iter()
            .map(|flat| flat_to_mat4d(flat)
                .ok_or_else(|| PyValueError::new_err("Matrix4d requires exactly 16 floats")))
            .collect::<PyResult<_>>()?;
        Ok(Self { inner: Array::from(mats) })
    }

    fn __len__(&self) -> usize { self.inner.len() }

    fn __getitem__(&self, py: Python<'_>, key: &Bound<'_, PyAny>) -> PyResult<PyObject> {
        if let Ok(i) = key.extract::<isize>() {
            let idx = norm_idx(i, self.inner.len())?;
            Ok(mat4d_to_flat(&self.inner.as_slice()[idx]).into_py(py))
        } else {
            Err(PyTypeError::new_err("index must be int"))
        }
    }

    fn __setitem__(&mut self, key: &Bound<'_, PyAny>, value: &Bound<'_, PyAny>) -> PyResult<()> {
        if let Ok(i) = key.extract::<isize>() {
            let idx = norm_idx(i, self.inner.len())?;
            let flat: Vec<f64> = value.extract()?;
            let m = flat_to_mat4d(&flat)
                .ok_or_else(|| PyValueError::new_err("Matrix4d requires 16 floats"))?;
            self.inner.make_unique();
            self.inner.as_mut_slice()
                .ok_or_else(|| PyValueError::new_err("array is not uniquely owned"))?[idx] = m;
            Ok(())
        } else {
            Err(PyTypeError::new_err("index must be int"))
        }
    }

    fn __iter__(slf: PyRef<'_, Self>) -> PyResult<Py<VtStringIter>> {
        let data = slf.inner.as_slice().iter().map(|m| format!("{:?}", mat4d_to_flat(m))).collect();
        Py::new(slf.py(), VtStringIter::new_from_data(data))
    }

    fn __eq__(&self, other: &Self) -> bool { self.inner.as_slice() == other.inner.as_slice() }
    fn __ne__(&self, other: &Self) -> bool { self.inner.as_slice() != other.inner.as_slice() }
    fn __repr__(&self) -> String { format!("Vt.Matrix4dArray([{} items])", self.inner.len()) }
    fn __str__(&self) -> String { format!("[{} Matrix4d]", self.inner.len()) }
}

#[pyclass(name = "Matrix4fArray", module = "pxr.Vt")]
#[derive(Clone)]
pub struct PyMatrix4fArray { inner: Array<usd_gf::Matrix4f> }

#[pymethods]
impl PyMatrix4fArray {
    #[new]
    #[pyo3(signature = (arg = None))]
    fn new(arg: Option<&Bound<'_, PyAny>>) -> PyResult<Self> {
        let Some(obj) = arg else {
            return Ok(Self { inner: Array::new() });
        };
        if let Ok(n) = obj.extract::<usize>() {
            return Ok(Self { inner: Array::from_elem(usd_gf::Matrix4f::identity(), n) });
        }
        let items: Vec<Vec<f32>> = obj.extract()
            .map_err(|_| PyValueError::new_err("expected int or list of 16-float lists"))?;
        let mats: Vec<usd_gf::Matrix4f> = items.iter()
            .map(|flat| flat_to_mat4f(flat)
                .ok_or_else(|| PyValueError::new_err("Matrix4f requires exactly 16 floats")))
            .collect::<PyResult<_>>()?;
        Ok(Self { inner: Array::from(mats) })
    }

    fn __len__(&self) -> usize { self.inner.len() }

    fn __getitem__(&self, py: Python<'_>, key: &Bound<'_, PyAny>) -> PyResult<PyObject> {
        if let Ok(i) = key.extract::<isize>() {
            let idx = norm_idx(i, self.inner.len())?;
            Ok(mat4f_to_flat(&self.inner.as_slice()[idx]).into_py(py))
        } else {
            Err(PyTypeError::new_err("index must be int"))
        }
    }

    fn __setitem__(&mut self, key: &Bound<'_, PyAny>, value: &Bound<'_, PyAny>) -> PyResult<()> {
        if let Ok(i) = key.extract::<isize>() {
            let idx = norm_idx(i, self.inner.len())?;
            let flat: Vec<f32> = value.extract()?;
            let m = flat_to_mat4f(&flat)
                .ok_or_else(|| PyValueError::new_err("Matrix4f requires 16 floats"))?;
            self.inner.make_unique();
            self.inner.as_mut_slice()
                .ok_or_else(|| PyValueError::new_err("array is not uniquely owned"))?[idx] = m;
            Ok(())
        } else {
            Err(PyTypeError::new_err("index must be int"))
        }
    }

    fn __iter__(slf: PyRef<'_, Self>) -> PyResult<Py<VtStringIter>> {
        let data = slf.inner.as_slice().iter().map(|m| format!("{:?}", mat4f_to_flat(m))).collect();
        Py::new(slf.py(), VtStringIter::new_from_data(data))
    }

    fn __eq__(&self, other: &Self) -> bool { self.inner.as_slice() == other.inner.as_slice() }
    fn __ne__(&self, other: &Self) -> bool { self.inner.as_slice() != other.inner.as_slice() }
    fn __repr__(&self) -> String { format!("Vt.Matrix4fArray([{} items])", self.inner.len()) }
    fn __str__(&self) -> String { format!("[{} Matrix4f]", self.inner.len()) }
}

// ============================================================================
// VtDictionary ↔ Python dict
// ============================================================================

/// Convert a Rust `Dictionary` to a Python `dict` (recursive).
pub fn dict_to_py(py: Python<'_>, d: &Dictionary) -> PyResult<PyObject> {
    let dict = PyDict::new(py);
    for (k, v) in d.iter() {
        dict.set_item(k, value_to_py(py, v)?)?;
    }
    Ok(dict.into())
}

/// Convert a Python object to a Rust `Value`.
pub fn py_to_value(obj: &Bound<'_, PyAny>) -> PyResult<Value> {
    if obj.is_none() { return Ok(Value::empty()); }
    // bool before int (Python bool subclasses int)
    if let Ok(b) = obj.extract::<bool>() { return Ok(Value::new(b)); }
    if let Ok(i) = obj.extract::<i64>() {
        if i >= i64::from(i32::MIN) && i <= i64::from(i32::MAX) {
            return Ok(Value::new(i as i32));
        }
        return Ok(Value::new(i));
    }
    if let Ok(f) = obj.extract::<f64>() { return Ok(Value::from_f64(f)); }
    if let Ok(s) = obj.extract::<String>() { return Ok(Value::new(s)); }
    if let Ok(d) = obj.downcast::<PyDict>() {
        return Ok(Value::from_dictionary(py_dict_to_dict(d)?.to_hash_map()));
    }
    Ok(Value::empty())
}

fn py_dict_to_dict(d: &Bound<'_, PyDict>) -> PyResult<Dictionary> {
    let mut dict = Dictionary::new();
    for (k, v) in d.iter() {
        let key: String = k.extract()
            .map_err(|_| PyTypeError::new_err("VtDictionary keys must be strings"))?;
        dict.insert_value(key, py_to_value(&v)?);
    }
    Ok(dict)
}

fn value_to_py(py: Python<'_>, v: &Value) -> PyResult<PyObject> {
    if v.is_empty() { return Ok(py.None()); }
    if let Some(b) = v.get::<bool>()   { return Ok(b.into_py(py)); }
    if let Some(i) = v.get::<i32>()    { return Ok(i.into_py(py)); }
    if let Some(i) = v.get::<i64>()    { return Ok(i.into_py(py)); }
    if let Some(u) = v.get::<u64>()    { return Ok(u.into_py(py)); }
    if let Some(x) = v.get::<f64>()    { return Ok(x.into_py(py)); }
    if let Some(x) = v.get::<f32>()    { return Ok((*x as f64).into_py(py)); }
    if let Some(s) = v.get::<String>() { return Ok(s.into_py(py)); }
    if let Some(t) = v.get::<usd_tf::Token>() { return Ok(t.to_string().into_py(py)); }
    if let Some(d) = v.get::<usd_vt::Dictionary>() { return dict_to_py(py, d); }
    Ok(py.None())
}

/// Python-facing `VtDictionary` — wraps `Dictionary` and round-trips as Python dict.
#[pyclass(name = "Dictionary", module = "pxr.Vt")]
#[derive(Clone, Default)]
pub struct PyDictionary { inner: Dictionary }

#[pymethods]
impl PyDictionary {
    #[new]
    #[pyo3(signature = (d = None))]
    fn new(d: Option<&Bound<'_, PyDict>>) -> PyResult<Self> {
        Ok(Self { inner: match d { Some(pd) => py_dict_to_dict(pd)?, None => Dictionary::new() } })
    }

    #[pyo3(name = "AsDict")]
    fn as_dict(&self, py: Python<'_>) -> PyResult<PyObject> { dict_to_py(py, &self.inner) }

    fn __len__(&self) -> usize { self.inner.len() }

    fn __repr__(&self, py: Python<'_>) -> PyResult<String> {
        Ok(format!("Vt.Dictionary({})", dict_to_py(py, &self.inner)?.bind(py)))
    }
    fn __str__(&self, py: Python<'_>) -> PyResult<String> {
        Ok(format!("{}", dict_to_py(py, &self.inner)?.bind(py)))
    }

    fn __getitem__(&self, py: Python<'_>, key: &str) -> PyResult<PyObject> {
        self.inner.get(key)
            .ok_or_else(|| pyo3::exceptions::PyKeyError::new_err(key.to_owned()))
            .and_then(|v| value_to_py(py, v))
    }

    fn __setitem__(&mut self, key: &str, value: &Bound<'_, PyAny>) -> PyResult<()> {
        self.inner.insert_value(key.to_owned(), py_to_value(value)?);
        Ok(())
    }

    fn __contains__(&self, key: &str) -> bool { self.inner.contains_key(key) }
    fn __eq__(&self, other: &Self) -> bool { self.inner == other.inner }
    fn __ne__(&self, other: &Self) -> bool { self.inner != other.inner }

    fn keys(&self) -> Vec<String> { self.inner.keys().map(|k| k.clone()).collect() }
}

// ============================================================================
// Module registration
// ============================================================================

/// Register all `pxr.Vt` classes.
pub fn register(py: Python<'_>, m: &Bound<'_, PyModule>) -> PyResult<()> {
    let _ = py;

    m.add_class::<PyValue>()?;
    m.add_class::<PyDictionary>()?;

    // Scalar arrays
    m.add_class::<PyBoolArray>()?;
    m.add_class::<PyUCharArray>()?;
    m.add_class::<PyShortArray>()?;
    m.add_class::<PyUShortArray>()?;
    m.add_class::<PyIntArray>()?;
    m.add_class::<PyUIntArray>()?;
    m.add_class::<PyInt64Array>()?;
    m.add_class::<PyUInt64Array>()?;
    m.add_class::<PyFloatArray>()?;
    m.add_class::<PyDoubleArray>()?;
    m.add_class::<PyHalfArray>()?;

    // String / Token arrays
    m.add_class::<PyStringArray>()?;
    m.add_class::<PyTokenArray>()?;

    // Vec arrays
    m.add_class::<PyVec2fArray>()?;
    m.add_class::<PyVec3fArray>()?;
    m.add_class::<PyVec4fArray>()?;
    m.add_class::<PyVec2dArray>()?;
    m.add_class::<PyVec3dArray>()?;
    m.add_class::<PyVec4dArray>()?;
    m.add_class::<PyVec2iArray>()?;
    m.add_class::<PyVec3iArray>()?;
    m.add_class::<PyVec4iArray>()?;

    // Matrix arrays
    m.add_class::<PyMatrix4dArray>()?;
    m.add_class::<PyMatrix4fArray>()?;

    // Iterators (must be registered so PyO3 can handle iterator protocol)
    m.add_class::<VtBoolIter>()?;
    m.add_class::<VtI8Iter>()?;
    m.add_class::<VtU8Iter>()?;
    m.add_class::<VtI16Iter>()?;
    m.add_class::<VtU16Iter>()?;
    m.add_class::<VtI32Iter>()?;
    m.add_class::<VtU32Iter>()?;
    m.add_class::<VtI64Iter>()?;
    m.add_class::<VtU64Iter>()?;
    m.add_class::<VtF32Iter>()?;
    m.add_class::<VtF64Iter>()?;
    m.add_class::<VtStringIter>()?;

    Ok(())
}
