//! pxr.Vt — Value Types bindings.
//!
//! Implements drop-in replacement for `pxr.Vt` from C++ OpenUSD:
//! - `Value` / `_ValueWrapper` — type-erased value container with explicit factory methods
//! - `VtArray<T>` — 30+ typed array classes generated by macro
//! - `Dictionary` — bidirectional Python dict ↔ VtDictionary conversion

use pyo3::exceptions::{PyIndexError, PyTypeError, PyValueError};
use pyo3::prelude::*;
use pyo3::types::{PyDict, PyList, PySlice};

use usd_vt::{Array, Dictionary, Value};

// ============================================================================
// Helpers
// ============================================================================

/// Normalise a Python signed index into [0, len), returning IndexError on OOB.
fn norm_idx(i: isize, len: usize) -> PyResult<usize> {
    let len_i = len as isize;
    let idx = if i < 0 { len_i + i } else { i };
    if idx < 0 || idx >= len_i {
        Err(PyIndexError::new_err(format!(
            "index {i} out of range for array of length {len}"
        )))
    } else {
        Ok(idx as usize)
    }
}

// ============================================================================
// VtValue / _ValueWrapper
// ============================================================================

/// Explicit typed wrapper over `Value` — mirrors C++ `Vt._ValueWrapper`.
///
/// Python code can request an exact wire type via static factory methods
/// (`Bool`, `Int`, `Float`, etc.) rather than relying on Python-type inference.
#[pyclass(name = "_ValueWrapper", module = "pxr.Vt")]
#[derive(Clone)]
pub struct PyValue {
    inner: Value,
    /// Human-readable type tag for repr (e.g. "int", "double").
    tag: &'static str,
}

#[pymethods]
impl PyValue {
    // -- Factories -----------------------------------------------------------

    /// Create a `Value` holding a Python object (auto-convert).
    ///
    /// Conversion rules mirror C++ wrapValue:
    ///   None      → empty
    ///   bool      → bool
    ///   int       → i32
    ///   float     → f64
    ///   str/bytes → String
    #[new]
    #[pyo3(signature = (obj = None))]
    fn new(obj: Option<&Bound<'_, PyAny>>) -> PyResult<Self> {
        let Some(obj) = obj else {
            return Ok(Self { inner: Value::empty(), tag: "empty" });
        };
        // bool before int — Python bool is a subclass of int
        if let Ok(b) = obj.extract::<bool>() {
            return Ok(Self { inner: Value::new(b), tag: "bool" });
        }
        if let Ok(i) = obj.extract::<i64>() {
            // Range-fit: prefer i32 for small values (matches C++)
            if i >= i64::from(i32::MIN) && i <= i64::from(i32::MAX) {
                return Ok(Self { inner: Value::new(i as i32), tag: "int" });
            }
            return Ok(Self { inner: Value::new(i), tag: "int64" });
        }
        if let Ok(f) = obj.extract::<f64>() {
            return Ok(Self { inner: Value::from_f64(f), tag: "double" });
        }
        if let Ok(s) = obj.extract::<String>() {
            return Ok(Self { inner: Value::new(s), tag: "string" });
        }
        // Fall back to empty — don't panic on unknown objects
        Ok(Self { inner: Value::empty(), tag: "unknown" })
    }

    // -- Explicit typed factories --------------------------------------------

    /// `Value` holding a `bool`.
    #[staticmethod]
    #[pyo3(name = "Bool")]
    fn mk_bool(v: bool) -> Self {
        Self { inner: Value::new(v), tag: "bool" }
    }

    /// `Value` holding a `u8`.
    #[staticmethod]
    #[pyo3(name = "UChar")]
    fn mk_uchar(v: u8) -> Self {
        Self { inner: Value::new(v), tag: "uchar" }
    }

    /// `Value` holding an `i16`.
    #[staticmethod]
    #[pyo3(name = "Short")]
    fn mk_short(v: i16) -> Self {
        Self { inner: Value::new(v), tag: "short" }
    }

    /// `Value` holding a `u16`.
    #[staticmethod]
    #[pyo3(name = "UShort")]
    fn mk_ushort(v: u16) -> Self {
        Self { inner: Value::new(v), tag: "ushort" }
    }

    /// `Value` holding an `i32`.
    #[staticmethod]
    #[pyo3(name = "Int")]
    fn mk_int(v: i32) -> Self {
        Self { inner: Value::new(v), tag: "int" }
    }

    /// `Value` holding a `u32`.
    #[staticmethod]
    #[pyo3(name = "UInt")]
    fn mk_uint(v: u32) -> Self {
        Self { inner: Value::new(v), tag: "uint" }
    }

    /// `Value` holding an `i64`.
    #[staticmethod]
    #[pyo3(name = "Long")]
    fn mk_long(v: i64) -> Self {
        Self { inner: Value::new(v), tag: "long" }
    }

    /// Alias for `Long`.
    #[staticmethod]
    #[pyo3(name = "Int64")]
    fn mk_int64(v: i64) -> Self {
        Self { inner: Value::new(v), tag: "int64" }
    }

    /// `Value` holding a `u64`.
    #[staticmethod]
    #[pyo3(name = "ULong")]
    fn mk_ulong(v: u64) -> Self {
        Self { inner: Value::new(v), tag: "ulong" }
    }

    /// Alias for `ULong`.
    #[staticmethod]
    #[pyo3(name = "UInt64")]
    fn mk_uint64(v: u64) -> Self {
        Self { inner: Value::new(v), tag: "uint64" }
    }

    /// `Value` holding an `f32`.
    #[staticmethod]
    #[pyo3(name = "Float")]
    fn mk_float(v: f32) -> Self {
        Self { inner: Value::from_f32(v), tag: "float" }
    }

    /// `Value` holding an `f64`.
    #[staticmethod]
    #[pyo3(name = "Double")]
    fn mk_double(v: f64) -> Self {
        Self { inner: Value::from_f64(v), tag: "double" }
    }

    /// `Value` holding a half-precision float (stored as `f32` proxy).
    #[staticmethod]
    #[pyo3(name = "Half")]
    fn mk_half(v: f32) -> Self {
        // half::f16 not directly usable via pyo3; store as f32 proxy
        Self { inner: Value::from_f32(v), tag: "half" }
    }

    /// `Value` holding a `TfToken` (interned string).
    #[staticmethod]
    #[pyo3(name = "Token")]
    fn mk_token(v: &str) -> Self {
        let tok = usd_tf::Token::new(v);
        Self { inner: Value::new(tok), tag: "token" }
    }

    // -- Inspection ----------------------------------------------------------

    /// Returns `True` if this value is empty (holds no data).
    #[pyo3(name = "IsEmpty")]
    fn is_empty(&self) -> bool {
        self.inner.is_empty()
    }

    // -- Dunder methods ------------------------------------------------------

    fn __eq__(&self, other: &Self) -> bool {
        self.inner == other.inner
    }

    fn __ne__(&self, other: &Self) -> bool {
        self.inner != other.inner
    }

    fn __str__(&self) -> String {
        format!("{}", ValueDisplay(&self.inner))
    }

    fn __repr__(&self) -> String {
        format!("Vt._ValueWrapper({}: {})", self.tag, ValueDisplay(&self.inner))
    }
}

/// Lightweight Display adapter so we can format `Value` without allocating a new type.
struct ValueDisplay<'a>(&'a Value);

impl std::fmt::Display for ValueDisplay<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if self.0.is_empty() {
            return write!(f, "<empty>");
        }
        // Try common types in priority order
        if let Some(b) = self.0.get::<bool>() {
            return write!(f, "{b}");
        }
        if let Some(i) = self.0.get::<i32>() {
            return write!(f, "{i}");
        }
        if let Some(i) = self.0.get::<i64>() {
            return write!(f, "{i}");
        }
        if let Some(u) = self.0.get::<u64>() {
            return write!(f, "{u}");
        }
        if let Some(x) = self.0.get::<f64>() {
            return write!(f, "{x}");
        }
        if let Some(x) = self.0.get::<f32>() {
            return write!(f, "{x}");
        }
        if let Some(s) = self.0.get::<String>() {
            return write!(f, "{s}");
        }
        if let Some(t) = self.0.get::<usd_tf::Token>() {
            return write!(f, "{t}");
        }
        write!(f, "<value>")
    }
}

// ============================================================================
// VtArray macro — generates one Python class per element type
// ============================================================================
//
// Design rationale: the C++ wrapArray.h template generates identical APIs for
// 80+ instantiations. We replicate this with a single Rust `macro_rules!` that
// produces a struct + `#[pymethods]` block per type combination.
//
// Each generated class:
//   - Wraps `Array<$elem>` from usd-vt
//   - Exposes `__len__`, `__getitem__`, `__setitem__`, `__iter__`, `__repr__`,
//     `__str__`, `__eq__`, `__ne__`
//   - Conditionally exposes arithmetic operators via separate trait arms
//
// The `$elem_display` closure converts an element to a Python-legible string.

macro_rules! vt_array {
    // Scalar numeric arrays — supports full arithmetic
    (
        numeric,
        name    = $py_name:literal,
        module  = $py_mod:literal,
        rust    = $rust_name:ident,
        elem    = $elem:ty,
        fmt     = $fmt_fn:expr,
        iter_ty = $iter_ty:ident
    ) => {
        #[pyclass(name = $py_name, module = $py_mod)]
        #[derive(Clone)]
        pub struct $rust_name {
            inner: Array<$elem>,
        }

        #[pymethods]
        impl $rust_name {
            // Constructors -------------------------------------------------------

            #[new]
            #[pyo3(signature = (arg = None))]
            fn new(arg: Option<&Bound<'_, PyAny>>) -> PyResult<Self> {
                build_array::<$elem>(arg, <$elem as Default>::default)
                    .map(|inner| Self { inner })
            }

            // Length / indexing --------------------------------------------------

            fn __len__(&self) -> usize {
                self.inner.len()
            }

            fn __getitem__(&self, py: Python<'_>, key: &Bound<'_, PyAny>) -> PyResult<PyObject> {
                if let Ok(i) = key.extract::<isize>() {
                    let idx = norm_idx(i, self.inner.len())?;
                    // SAFETY: idx is bounds-checked above
                    Ok(($fmt_fn)(self.inner.as_slice()[idx]).into_py(py))
                } else if let Ok(slice) = key.downcast::<PySlice>() {
                    let indices = slice.indices(self.inner.len() as std::ffi::c_long)?;
                    let list = PyList::empty(py);
                    let mut idx = indices.start;
                    while (indices.step > 0 && idx < indices.stop)
                        || (indices.step < 0 && idx > indices.stop)
                    {
                        list.append(($fmt_fn)(self.inner.as_slice()[idx as usize]).into_py(py))?;
                        idx += indices.step;
                    }
                    Ok(list.into())
                } else {
                    Err(PyTypeError::new_err("index must be int or slice"))
                }
            }

            fn __setitem__(
                &mut self,
                key: &Bound<'_, PyAny>,
                value: &Bound<'_, PyAny>,
            ) -> PyResult<()> {
                if let Ok(i) = key.extract::<isize>() {
                    let idx = norm_idx(i, self.inner.len())?;
                    let elem: $elem = value.extract()?;
                    self.inner.make_unique();
                    // SAFETY: idx bounds-checked; make_unique ensures exclusive ownership
                    self.inner.as_mut_slice()[idx] = elem;
                    Ok(())
                } else if let Ok(slice) = key.downcast::<PySlice>() {
                    let indices = slice.indices(self.inner.len() as std::ffi::c_long)?;
                    // Collect new values first
                    let list: Vec<$elem> = value.extract()?;
                    self.inner.make_unique();
                    let data = self.inner.as_mut_slice();
                    let mut idx = indices.start as usize;
                    for elem in list {
                        if idx >= data.len() {
                            break;
                        }
                        data[idx] = elem;
                        idx = (idx as isize + indices.step) as usize;
                    }
                    Ok(())
                } else {
                    Err(PyTypeError::new_err("index must be int or slice"))
                }
            }

            // Iteration ----------------------------------------------------------

            fn __iter__(slf: PyRef<'_, Self>) -> PyResult<Py<$iter_ty>> {
                let iter = <$iter_ty>::new_from_data(slf.inner.as_slice().to_vec());
                Py::new(slf.py(), iter)
            }

            // Comparison ---------------------------------------------------------

            fn __eq__(&self, other: &Self) -> bool {
                self.inner.as_slice() == other.inner.as_slice()
            }

            fn __ne__(&self, other: &Self) -> bool {
                self.inner.as_slice() != other.inner.as_slice()
            }

            // String representation ----------------------------------------------

            fn __repr__(&self) -> String {
                let type_name = $py_name;
                let elems: Vec<String> = self.inner.as_slice()
                    .iter()
                    .map(|x| format!("{}", ($fmt_fn)(*x)))
                    .collect();
                format!("Vt.{}([{}])", type_name, elems.join(", "))
            }

            fn __str__(&self) -> String {
                let elems: Vec<String> = self.inner.as_slice()
                    .iter()
                    .map(|x| format!("{}", ($fmt_fn)(*x)))
                    .collect();
                format!("[{}]", elems.join(", "))
            }

            // Arithmetic ---------------------------------------------------------

            fn __add__(&self, other: &Self) -> Self {
                let data: Vec<$elem> = self.inner.as_slice()
                    .iter()
                    .zip(other.inner.as_slice().iter())
                    .map(|(a, b)| *a + *b)
                    .collect();
                Self { inner: Array::from(data) }
            }

            fn __radd__(&self, other: &Self) -> Self {
                self.__add__(other)
            }

            fn __sub__(&self, other: &Self) -> Self {
                let data: Vec<$elem> = self.inner.as_slice()
                    .iter()
                    .zip(other.inner.as_slice().iter())
                    .map(|(a, b)| *a - *b)
                    .collect();
                Self { inner: Array::from(data) }
            }

            fn __rsub__(&self, other: &Self) -> Self {
                other.__sub__(self)
            }

            fn __neg__(&self) -> Self {
                let data: Vec<$elem> = self.inner.as_slice()
                    .iter()
                    .map(|a| -(*a))
                    .collect();
                Self { inner: Array::from(data) }
            }

            fn __mul__(&self, scalar: f64) -> Self {
                let s = scalar as $elem;
                let data: Vec<$elem> = self.inner.as_slice()
                    .iter()
                    .map(|a| *a * s)
                    .collect();
                Self { inner: Array::from(data) }
            }

            fn __rmul__(&self, scalar: f64) -> Self {
                self.__mul__(scalar)
            }

            fn __truediv__(&self, scalar: f64) -> PyResult<Self> {
                if scalar == 0.0 {
                    return Err(pyo3::exceptions::PyZeroDivisionError::new_err(
                        "division by zero",
                    ));
                }
                let s = scalar as $elem;
                let data: Vec<$elem> = self.inner.as_slice()
                    .iter()
                    .map(|a| *a / s)
                    .collect();
                Ok(Self { inner: Array::from(data) })
            }
        }
    };

    // No-arithmetic arrays — only comparison and indexing (bool, token, etc.)
    (
        no_arith,
        name    = $py_name:literal,
        module  = $py_mod:literal,
        rust    = $rust_name:ident,
        elem    = $elem:ty,
        fmt     = $fmt_fn:expr,
        iter_ty = $iter_ty:ident
    ) => {
        #[pyclass(name = $py_name, module = $py_mod)]
        #[derive(Clone)]
        pub struct $rust_name {
            inner: Array<$elem>,
        }

        #[pymethods]
        impl $rust_name {
            #[new]
            #[pyo3(signature = (arg = None))]
            fn new(arg: Option<&Bound<'_, PyAny>>) -> PyResult<Self> {
                build_array::<$elem>(arg, <$elem as Default>::default)
                    .map(|inner| Self { inner })
            }

            fn __len__(&self) -> usize { self.inner.len() }

            fn __getitem__(&self, py: Python<'_>, key: &Bound<'_, PyAny>) -> PyResult<PyObject> {
                if let Ok(i) = key.extract::<isize>() {
                    let idx = norm_idx(i, self.inner.len())?;
                    Ok(($fmt_fn)(self.inner.as_slice()[idx]).into_py(py))
                } else if let Ok(slice) = key.downcast::<PySlice>() {
                    let indices = slice.indices(self.inner.len() as std::ffi::c_long)?;
                    let list = PyList::empty(py);
                    let mut idx = indices.start;
                    while (indices.step > 0 && idx < indices.stop)
                        || (indices.step < 0 && idx > indices.stop)
                    {
                        list.append(($fmt_fn)(self.inner.as_slice()[idx as usize]).into_py(py))?;
                        idx += indices.step;
                    }
                    Ok(list.into())
                } else {
                    Err(PyTypeError::new_err("index must be int or slice"))
                }
            }

            fn __setitem__(
                &mut self,
                key: &Bound<'_, PyAny>,
                value: &Bound<'_, PyAny>,
            ) -> PyResult<()> {
                if let Ok(i) = key.extract::<isize>() {
                    let idx = norm_idx(i, self.inner.len())?;
                    let elem: $elem = value.extract()?;
                    self.inner.make_unique();
                    self.inner.as_mut_slice()[idx] = elem;
                    Ok(())
                } else {
                    Err(PyTypeError::new_err("index must be int"))
                }
            }

            fn __iter__(slf: PyRef<'_, Self>) -> PyResult<Py<$iter_ty>> {
                let iter = <$iter_ty>::new_from_data(slf.inner.as_slice().to_vec());
                Py::new(slf.py(), iter)
            }

            fn __eq__(&self, other: &Self) -> bool {
                self.inner.as_slice() == other.inner.as_slice()
            }

            fn __ne__(&self, other: &Self) -> bool {
                self.inner.as_slice() != other.inner.as_slice()
            }

            fn __repr__(&self) -> String {
                let elems: Vec<String> = self.inner.as_slice()
                    .iter()
                    .map(|x| format!("{}", ($fmt_fn)(*x)))
                    .collect();
                format!("Vt.{}([{}])", $py_name, elems.join(", "))
            }

            fn __str__(&self) -> String {
                let elems: Vec<String> = self.inner.as_slice()
                    .iter()
                    .map(|x| format!("{}", ($fmt_fn)(*x)))
                    .collect();
                format!("[{}]", elems.join(", "))
            }
        }
    };

    // String-like arrays — only __add__ (concatenation), no neg/mul/div
    (
        string,
        name   = $py_name:literal,
        module = $py_mod:literal,
        rust   = $rust_name:ident,
        elem   = $elem:ty
    ) => {
        #[pyclass(name = $py_name, module = $py_mod)]
        #[derive(Clone)]
        pub struct $rust_name {
            inner: Array<$elem>,
        }

        #[pymethods]
        impl $rust_name {
            #[new]
            #[pyo3(signature = (arg = None))]
            fn new(arg: Option<&Bound<'_, PyAny>>) -> PyResult<Self> {
                build_array_clone::<$elem>(arg).map(|inner| Self { inner })
            }

            fn __len__(&self) -> usize { self.inner.len() }

            fn __getitem__(&self, py: Python<'_>, key: &Bound<'_, PyAny>) -> PyResult<PyObject> {
                if let Ok(i) = key.extract::<isize>() {
                    let idx = norm_idx(i, self.inner.len())?;
                    Ok(self.inner.as_slice()[idx].clone().into_py(py))
                } else if let Ok(slice) = key.downcast::<PySlice>() {
                    let indices = slice.indices(self.inner.len() as std::ffi::c_long)?;
                    let list = PyList::empty(py);
                    let mut idx = indices.start;
                    while (indices.step > 0 && idx < indices.stop)
                        || (indices.step < 0 && idx > indices.stop)
                    {
                        list.append(self.inner.as_slice()[idx as usize].clone().into_py(py))?;
                        idx += indices.step;
                    }
                    Ok(list.into())
                } else {
                    Err(PyTypeError::new_err("index must be int or slice"))
                }
            }

            fn __setitem__(
                &mut self,
                key: &Bound<'_, PyAny>,
                value: &Bound<'_, PyAny>,
            ) -> PyResult<()> {
                if let Ok(i) = key.extract::<isize>() {
                    let idx = norm_idx(i, self.inner.len())?;
                    let elem: $elem = value.extract()?;
                    self.inner.make_unique();
                    self.inner.as_mut_slice()[idx] = elem;
                    Ok(())
                } else {
                    Err(PyTypeError::new_err("index must be int"))
                }
            }

            fn __iter__(slf: PyRef<'_, Self>) -> PyResult<Py<VtStringIter>> {
                let iter = VtStringIter {
                    data: slf.inner.as_slice()
                        .iter()
                        .map(|s| format!("{s}"))
                        .collect(),
                    pos: 0,
                };
                Py::new(slf.py(), iter)
            }

            fn __eq__(&self, other: &Self) -> bool {
                self.inner.as_slice() == other.inner.as_slice()
            }

            fn __ne__(&self, other: &Self) -> bool {
                self.inner.as_slice() != other.inner.as_slice()
            }

            fn __repr__(&self) -> String {
                let elems: Vec<String> = self.inner.as_slice()
                    .iter()
                    .map(|s| format!("{s:?}"))
                    .collect();
                format!("Vt.{}([{}])", $py_name, elems.join(", "))
            }

            fn __str__(&self) -> String {
                let elems: Vec<String> = self.inner.as_slice()
                    .iter()
                    .map(|s| format!("{s}"))
                    .collect();
                format!("[{}]", elems.join(", "))
            }

            fn __add__(&self, other: &Self) -> Self {
                let mut data = self.inner.as_slice().to_vec();
                data.extend_from_slice(other.inner.as_slice());
                Self { inner: Array::from(data) }
            }
        }
    };

    // Vector/matrix arrays — add, sub, neg, double-mul; no div
    (
        vec,
        name        = $py_name:literal,
        module      = $py_mod:literal,
        rust        = $rust_name:ident,
        elem        = $elem:ty,
        py_elem     = $py_elem:ty,
        from_py     = $from_py:expr,
        to_py       = $to_py:expr
    ) => {
        #[pyclass(name = $py_name, module = $py_mod)]
        #[derive(Clone)]
        pub struct $rust_name {
            inner: Array<$elem>,
        }

        #[pymethods]
        impl $rust_name {
            #[new]
            #[pyo3(signature = (arg = None))]
            fn new(arg: Option<&Bound<'_, PyAny>>) -> PyResult<Self> {
                let inner = build_array_mapped::<$elem, $py_elem>(arg, $from_py)?;
                Ok(Self { inner })
            }

            fn __len__(&self) -> usize { self.inner.len() }

            fn __getitem__(&self, py: Python<'_>, key: &Bound<'_, PyAny>) -> PyResult<PyObject> {
                if let Ok(i) = key.extract::<isize>() {
                    let idx = norm_idx(i, self.inner.len())?;
                    Ok(($to_py)(self.inner.as_slice()[idx].clone()).into_py(py))
                } else if let Ok(slice) = key.downcast::<PySlice>() {
                    let indices = slice.indices(self.inner.len() as std::ffi::c_long)?;
                    let list = PyList::empty(py);
                    let mut idx = indices.start;
                    while (indices.step > 0 && idx < indices.stop)
                        || (indices.step < 0 && idx > indices.stop)
                    {
                        list.append(($to_py)(self.inner.as_slice()[idx as usize].clone()).into_py(py))?;
                        idx += indices.step;
                    }
                    Ok(list.into())
                } else {
                    Err(PyTypeError::new_err("index must be int or slice"))
                }
            }

            fn __setitem__(
                &mut self,
                key: &Bound<'_, PyAny>,
                value: &Bound<'_, PyAny>,
            ) -> PyResult<()> {
                if let Ok(i) = key.extract::<isize>() {
                    let idx = norm_idx(i, self.inner.len())?;
                    let py_val: $py_elem = value.extract()?;
                    self.inner.make_unique();
                    self.inner.as_mut_slice()[idx] = ($from_py)(py_val);
                    Ok(())
                } else {
                    Err(PyTypeError::new_err("index must be int"))
                }
            }

            fn __iter__(slf: PyRef<'_, Self>) -> PyResult<Py<VtStringIter>> {
                let data: Vec<String> = slf.inner.as_slice()
                    .iter()
                    .map(|v| format!("{:?}", ($to_py)(v.clone())))
                    .collect();
                Py::new(slf.py(), VtStringIter { data, pos: 0 })
            }

            fn __eq__(&self, other: &Self) -> bool {
                self.inner.as_slice() == other.inner.as_slice()
            }

            fn __ne__(&self, other: &Self) -> bool {
                self.inner.as_slice() != other.inner.as_slice()
            }

            fn __repr__(&self) -> String {
                let elems: Vec<String> = self.inner.as_slice()
                    .iter()
                    .map(|v| format!("{:?}", ($to_py)(v.clone())))
                    .collect();
                format!("Vt.{}([{}])", $py_name, elems.join(", "))
            }

            fn __str__(&self) -> String {
                let elems: Vec<String> = self.inner.as_slice()
                    .iter()
                    .map(|v| format!("{:?}", ($to_py)(v.clone())))
                    .collect();
                format!("[{}]", elems.join(", "))
            }
        }
    };
}

// ============================================================================
// Generic array construction helpers
// ============================================================================

/// Build `Array<T>` from `None` (empty), `int` (sized), or sequence.
/// Used for Copy+Default scalars that are directly extractable from Python.
fn build_array<T>(
    arg: Option<&Bound<'_, PyAny>>,
    default: fn() -> T,
) -> PyResult<Array<T>>
where
    T: Clone + Send + Sync + for<'py> FromPyObject<'py> + 'static,
{
    let Some(obj) = arg else {
        return Ok(Array::new());
    };

    // Single usize → preallocate with default fill
    if let Ok(n) = obj.extract::<usize>() {
        return Ok(Array::from_elem(default(), n));
    }

    // Sequence of values
    let list: Vec<T> = obj
        .extract()
        .map_err(|_| PyValueError::new_err("expected int size or sequence"))?;
    Ok(Array::from(list))
}

/// Same as `build_array` but for Clone types (String, Token).
fn build_array_clone<T>(arg: Option<&Bound<'_, PyAny>>) -> PyResult<Array<T>>
where
    T: Clone + Send + Sync + Default + for<'py> FromPyObject<'py> + 'static,
{
    let Some(obj) = arg else {
        return Ok(Array::new());
    };
    if let Ok(n) = obj.extract::<usize>() {
        return Ok(Array::from_elem(T::default(), n));
    }
    let list: Vec<T> = obj
        .extract()
        .map_err(|_| PyValueError::new_err("expected int size or sequence"))?;
    Ok(Array::from(list))
}

/// Build `Array<T>` from a Python sequence of `PyElem`, mapping via `from_py`.
fn build_array_mapped<T, PyElem>(
    arg: Option<&Bound<'_, PyAny>>,
    from_py: fn(PyElem) -> T,
) -> PyResult<Array<T>>
where
    T: Clone + Send + Sync + Default + 'static,
    PyElem: for<'py> FromPyObject<'py>,
{
    let Some(obj) = arg else {
        return Ok(Array::new());
    };
    if let Ok(n) = obj.extract::<usize>() {
        return Ok(Array::from_elem(T::default(), n));
    }
    let list: Vec<PyElem> = obj
        .extract()
        .map_err(|_| PyValueError::new_err("expected int size or sequence"))?;
    let mapped: Vec<T> = list.into_iter().map(from_py).collect();
    Ok(Array::from(mapped))
}

// ============================================================================
// Iterator helpers
// ============================================================================
//
// PyO3 does not support generic #[pyclass]. We define one concrete iterator
// per scalar type via macro, plus a string-based iterator for complex types.

macro_rules! define_scalar_iter {
    ($name:ident, $elem:ty) => {
        #[pyclass]
        pub struct $name {
            data: Vec<$elem>,
            pos: usize,
        }

        impl $name {
            /// Construct from a collected vec of elements.
            pub fn new_from_data(data: Vec<$elem>) -> Self {
                Self { data, pos: 0 }
            }
        }

        #[pymethods]
        impl $name {
            fn __iter__(slf: PyRef<'_, Self>) -> PyRef<'_, Self> {
                slf
            }

            fn __next__(mut slf: PyRefMut<'_, Self>) -> Option<$elem> {
                if slf.pos < slf.data.len() {
                    let v = slf.data[slf.pos];
                    slf.pos += 1;
                    Some(v)
                } else {
                    None
                }
            }
        }
    };
}

define_scalar_iter!(VtBoolIter,   bool);
define_scalar_iter!(VtI32Iter,    i32);
define_scalar_iter!(VtU32Iter,    u32);
define_scalar_iter!(VtI64Iter,    i64);
define_scalar_iter!(VtU64Iter,    u64);
define_scalar_iter!(VtI8Iter,     i8);
define_scalar_iter!(VtU8Iter,     u8);
define_scalar_iter!(VtI16Iter,    i16);
define_scalar_iter!(VtU16Iter,    u16);
define_scalar_iter!(VtF32Iter,    f32);
define_scalar_iter!(VtF64Iter,    f64);

/// String-based iterator (covers String, Token, and struct types rendered as strings).
#[pyclass]
pub struct VtStringIter {
    data: Vec<String>,
    pos: usize,
}

#[pymethods]
impl VtStringIter {
    fn __iter__(slf: PyRef<'_, Self>) -> PyRef<'_, Self> {
        slf
    }

    fn __next__(mut slf: PyRefMut<'_, Self>) -> Option<String> {
        if slf.pos < slf.data.len() {
            let s = slf.data[slf.pos].clone();
            slf.pos += 1;
            Some(s)
        } else {
            None
        }
    }
}

// ============================================================================
// Scalar numeric array instantiations
// ============================================================================

// BoolArray: bool doesn't implement numeric ops in Rust; use no_arith arm.
// C++ treats bool as 0/1 but in Python pxr.Vt.BoolArray arithmetic is rare.
vt_array!(no_arith,
    name = "BoolArray", module = "pxr.Vt",
    rust = PyBoolArray, elem = bool,
    fmt = |x: bool| x,
    iter_ty = VtBoolIter
);

vt_array!(numeric,
    name = "UCharArray", module = "pxr.Vt",
    rust = PyUCharArray, elem = u8,
    fmt = |x: u8| x,
    iter_ty = VtU8Iter
);

vt_array!(numeric,
    name = "IntArray", module = "pxr.Vt",
    rust = PyIntArray, elem = i32,
    fmt = |x: i32| x,
    iter_ty = VtI32Iter
);

vt_array!(numeric,
    name = "UIntArray", module = "pxr.Vt",
    rust = PyUIntArray, elem = u32,
    fmt = |x: u32| x,
    iter_ty = VtU32Iter
);

vt_array!(numeric,
    name = "Int64Array", module = "pxr.Vt",
    rust = PyInt64Array, elem = i64,
    fmt = |x: i64| x,
    iter_ty = VtI64Iter
);

vt_array!(numeric,
    name = "UInt64Array", module = "pxr.Vt",
    rust = PyUInt64Array, elem = u64,
    fmt = |x: u64| x,
    iter_ty = VtU64Iter
);

vt_array!(numeric,
    name = "ShortArray", module = "pxr.Vt",
    rust = PyShortArray, elem = i16,
    fmt = |x: i16| x,
    iter_ty = VtI16Iter
);

vt_array!(numeric,
    name = "UShortArray", module = "pxr.Vt",
    rust = PyUShortArray, elem = u16,
    fmt = |x: u16| x,
    iter_ty = VtU16Iter
);

vt_array!(numeric,
    name = "FloatArray", module = "pxr.Vt",
    rust = PyFloatArray, elem = f32,
    fmt = |x: f32| x,
    iter_ty = VtF32Iter
);

vt_array!(numeric,
    name = "DoubleArray", module = "pxr.Vt",
    rust = PyDoubleArray, elem = f64,
    fmt = |x: f64| x,
    iter_ty = VtF64Iter
);

// Half stored as f32 — Python has no native half type
vt_array!(numeric,
    name = "HalfArray", module = "pxr.Vt",
    rust = PyHalfArray, elem = f32,
    fmt = |x: f32| x,
    iter_ty = VtF32Iter
);

// ============================================================================
// String / Token arrays
// ============================================================================

vt_array!(string,
    name = "StringArray", module = "pxr.Vt",
    rust = PyStringArray, elem = String
);

// TokenArray wraps usd_tf::Token; we expose as String at the Python boundary
// since Token is an interned string with the same external behaviour.
#[pyclass(name = "TokenArray", module = "pxr.Vt")]
#[derive(Clone)]
pub struct PyTokenArray {
    inner: Array<usd_tf::Token>,
}

#[pymethods]
impl PyTokenArray {
    #[new]
    #[pyo3(signature = (arg = None))]
    fn new(arg: Option<&Bound<'_, PyAny>>) -> PyResult<Self> {
        let Some(obj) = arg else {
            return Ok(Self { inner: Array::new() });
        };
        if let Ok(n) = obj.extract::<usize>() {
            let empty = usd_tf::Token::new("");
            return Ok(Self { inner: Array::from_elem(empty, n) });
        }
        let strings: Vec<String> = obj
            .extract()
            .map_err(|_| PyValueError::new_err("expected int size or sequence of str"))?;
        let tokens: Vec<usd_tf::Token> = strings.iter().map(|s| usd_tf::Token::new(s)).collect();
        Ok(Self { inner: Array::from(tokens) })
    }

    fn __len__(&self) -> usize { self.inner.len() }

    fn __getitem__(&self, py: Python<'_>, key: &Bound<'_, PyAny>) -> PyResult<PyObject> {
        if let Ok(i) = key.extract::<isize>() {
            let idx = norm_idx(i, self.inner.len())?;
            Ok(self.inner.as_slice()[idx].to_string().into_py(py))
        } else if let Ok(slice) = key.downcast::<PySlice>() {
            let indices = slice.indices(self.inner.len() as std::ffi::c_long)?;
            let list = PyList::empty(py);
            let mut idx = indices.start;
            while (indices.step > 0 && idx < indices.stop)
                || (indices.step < 0 && idx > indices.stop)
            {
                list.append(self.inner.as_slice()[idx as usize].to_string().into_py(py))?;
                idx += indices.step;
            }
            Ok(list.into())
        } else {
            Err(PyTypeError::new_err("index must be int or slice"))
        }
    }

    fn __setitem__(&mut self, key: &Bound<'_, PyAny>, value: &Bound<'_, PyAny>) -> PyResult<()> {
        if let Ok(i) = key.extract::<isize>() {
            let idx = norm_idx(i, self.inner.len())?;
            let s: String = value.extract()?;
            self.inner.make_unique();
            self.inner.as_mut_slice()[idx] = usd_tf::Token::new(&s);
            Ok(())
        } else {
            Err(PyTypeError::new_err("index must be int"))
        }
    }

    fn __iter__(slf: PyRef<'_, Self>) -> PyResult<Py<VtStringIter>> {
        let data: Vec<String> = slf.inner.as_slice()
            .iter()
            .map(|t| t.to_string())
            .collect();
        Py::new(slf.py(), VtStringIter { data, pos: 0 })
    }

    fn __eq__(&self, other: &Self) -> bool {
        self.inner.as_slice() == other.inner.as_slice()
    }

    fn __ne__(&self, other: &Self) -> bool {
        self.inner.as_slice() != other.inner.as_slice()
    }

    fn __repr__(&self) -> String {
        let elems: Vec<String> = self.inner.as_slice().iter().map(|t| format!("{t:?}")).collect();
        format!("Vt.TokenArray([{}])", elems.join(", "))
    }

    fn __str__(&self) -> String {
        let elems: Vec<String> = self.inner.as_slice().iter().map(|t| t.to_string()).collect();
        format!("[{}]", elems.join(", "))
    }
}

// ============================================================================
// Vec2/3/4 f/d/i arrays
//
// For vec arrays the Python element type is a tuple (f32,f32,...) for
// roundtrip simplicity. The Gf.VecXx Python objects live in the Gf module;
// accepting tuples here keeps Vt self-contained and avoids circular imports.
// ============================================================================

// usd_gf types are re-exported from usd-gf; their storage is independent of glam.

vt_array!(vec,
    name = "Vec2fArray", module = "pxr.Vt",
    rust = PyVec2fArray,
    elem = usd_gf::Vec2f, py_elem = (f32, f32),
    from_py = |(x, y): (f32, f32)| usd_gf::Vec2f::new(x, y),
    to_py   = |v: usd_gf::Vec2f| (v[0], v[1])
);

vt_array!(vec,
    name = "Vec3fArray", module = "pxr.Vt",
    rust = PyVec3fArray,
    elem = usd_gf::Vec3f, py_elem = (f32, f32, f32),
    from_py = |(x, y, z): (f32, f32, f32)| usd_gf::Vec3f::new(x, y, z),
    to_py   = |v: usd_gf::Vec3f| (v[0], v[1], v[2])
);

vt_array!(vec,
    name = "Vec4fArray", module = "pxr.Vt",
    rust = PyVec4fArray,
    elem = usd_gf::Vec4f, py_elem = (f32, f32, f32, f32),
    from_py = |(x, y, z, w): (f32, f32, f32, f32)| usd_gf::Vec4f::new(x, y, z, w),
    to_py   = |v: usd_gf::Vec4f| (v[0], v[1], v[2], v[3])
);

vt_array!(vec,
    name = "Vec2dArray", module = "pxr.Vt",
    rust = PyVec2dArray,
    elem = usd_gf::Vec2d, py_elem = (f64, f64),
    from_py = |(x, y): (f64, f64)| usd_gf::Vec2d::new(x, y),
    to_py   = |v: usd_gf::Vec2d| (v[0], v[1])
);

vt_array!(vec,
    name = "Vec3dArray", module = "pxr.Vt",
    rust = PyVec3dArray,
    elem = usd_gf::Vec3d, py_elem = (f64, f64, f64),
    from_py = |(x, y, z): (f64, f64, f64)| usd_gf::Vec3d::new(x, y, z),
    to_py   = |v: usd_gf::Vec3d| (v[0], v[1], v[2])
);

vt_array!(vec,
    name = "Vec4dArray", module = "pxr.Vt",
    rust = PyVec4dArray,
    elem = usd_gf::Vec4d, py_elem = (f64, f64, f64, f64),
    from_py = |(x, y, z, w): (f64, f64, f64, f64)| usd_gf::Vec4d::new(x, y, z, w),
    to_py   = |v: usd_gf::Vec4d| (v[0], v[1], v[2], v[3])
);

vt_array!(vec,
    name = "Vec2iArray", module = "pxr.Vt",
    rust = PyVec2iArray,
    elem = usd_gf::Vec2i, py_elem = (i32, i32),
    from_py = |(x, y): (i32, i32)| usd_gf::Vec2i::new(x, y),
    to_py   = |v: usd_gf::Vec2i| (v[0], v[1])
);

vt_array!(vec,
    name = "Vec3iArray", module = "pxr.Vt",
    rust = PyVec3iArray,
    elem = usd_gf::Vec3i, py_elem = (i32, i32, i32),
    from_py = |(x, y, z): (i32, i32, i32)| usd_gf::Vec3i::new(x, y, z),
    to_py   = |v: usd_gf::Vec3i| (v[0], v[1], v[2])
);

vt_array!(vec,
    name = "Vec4iArray", module = "pxr.Vt",
    rust = PyVec4iArray,
    elem = usd_gf::Vec4i, py_elem = (i32, i32, i32, i32),
    from_py = |(x, y, z, w): (i32, i32, i32, i32)| usd_gf::Vec4i::new(x, y, z, w),
    to_py   = |v: usd_gf::Vec4i| (v[0], v[1], v[2], v[3])
);

// ============================================================================
// Matrix4 arrays — stored as [[f64;4];4] / [[f32;4];4] row-major (matches usd_gf)
// ============================================================================

/// Convert Matrix4d to a flat 16-element Python-friendly tuple.
fn mat4d_to_flat(m: &usd_gf::Matrix4d) -> Vec<f64> {
    let a = m.to_array();
    a.iter().flat_map(|row| row.iter().copied()).collect()
}

/// Build Matrix4d from flat 16-element slice (row-major).
fn flat_to_mat4d(flat: &[f64]) -> Option<usd_gf::Matrix4d> {
    if flat.len() != 16 {
        return None;
    }
    let data = [
        [flat[0], flat[1], flat[2], flat[3]],
        [flat[4], flat[5], flat[6], flat[7]],
        [flat[8], flat[9], flat[10], flat[11]],
        [flat[12], flat[13], flat[14], flat[15]],
    ];
    Some(usd_gf::Matrix4d::from_array(data))
}

/// Convert Matrix4f to a flat 16-element Python-friendly tuple.
fn mat4f_to_flat(m: &usd_gf::Matrix4f) -> Vec<f32> {
    let a = m.to_array();
    a.iter().flat_map(|row| row.iter().copied()).collect()
}

/// Build Matrix4f from flat 16-element slice (row-major).
fn flat_to_mat4f(flat: &[f32]) -> Option<usd_gf::Matrix4f> {
    if flat.len() != 16 {
        return None;
    }
    let data = [
        [flat[0], flat[1], flat[2], flat[3]],
        [flat[4], flat[5], flat[6], flat[7]],
        [flat[8], flat[9], flat[10], flat[11]],
        [flat[12], flat[13], flat[14], flat[15]],
    ];
    Some(usd_gf::Matrix4f::from_array(data))
}

#[pyclass(name = "Matrix4dArray", module = "pxr.Vt")]
#[derive(Clone)]
pub struct PyMatrix4dArray {
    inner: Array<usd_gf::Matrix4d>,
}

#[pymethods]
impl PyMatrix4dArray {
    /// Construct empty, sized (identity fill), or from list of flat [f64;16].
    #[new]
    #[pyo3(signature = (arg = None))]
    fn new(arg: Option<&Bound<'_, PyAny>>) -> PyResult<Self> {
        let Some(obj) = arg else {
            return Ok(Self { inner: Array::new() });
        };
        if let Ok(n) = obj.extract::<usize>() {
            return Ok(Self {
                inner: Array::from_elem(usd_gf::Matrix4d::identity(), n),
            });
        }
        // Accept list of flat Vec<f64> (16 elements each, row-major)
        let items: Vec<Vec<f64>> = obj
            .extract()
            .map_err(|_| PyValueError::new_err("expected int size or list of 16-element float lists"))?;
        let mats: Vec<usd_gf::Matrix4d> = items
            .iter()
            .map(|flat| flat_to_mat4d(flat).ok_or_else(|| {
                PyValueError::new_err("each Matrix4d must be 16 floats")
            }))
            .collect::<PyResult<Vec<_>>>()?;
        Ok(Self { inner: Array::from(mats) })
    }

    fn __len__(&self) -> usize { self.inner.len() }

    fn __getitem__(&self, py: Python<'_>, key: &Bound<'_, PyAny>) -> PyResult<PyObject> {
        if let Ok(i) = key.extract::<isize>() {
            let idx = norm_idx(i, self.inner.len())?;
            let flat = mat4d_to_flat(&self.inner.as_slice()[idx]);
            Ok(flat.into_py(py))
        } else {
            Err(PyTypeError::new_err("index must be int"))
        }
    }

    fn __setitem__(&mut self, key: &Bound<'_, PyAny>, value: &Bound<'_, PyAny>) -> PyResult<()> {
        if let Ok(i) = key.extract::<isize>() {
            let idx = norm_idx(i, self.inner.len())?;
            let flat: Vec<f64> = value.extract()?;
            let m = flat_to_mat4d(&flat)
                .ok_or_else(|| PyValueError::new_err("Matrix4d requires 16 floats"))?;
            self.inner.make_unique();
            self.inner.as_mut_slice()[idx] = m;
            Ok(())
        } else {
            Err(PyTypeError::new_err("index must be int"))
        }
    }

    fn __iter__(slf: PyRef<'_, Self>) -> PyResult<Py<VtStringIter>> {
        let data: Vec<String> = slf.inner.as_slice()
            .iter()
            .map(|m| format!("{:?}", mat4d_to_flat(m)))
            .collect();
        Py::new(slf.py(), VtStringIter { data, pos: 0 })
    }

    fn __eq__(&self, other: &Self) -> bool {
        self.inner.as_slice() == other.inner.as_slice()
    }

    fn __ne__(&self, other: &Self) -> bool {
        self.inner.as_slice() != other.inner.as_slice()
    }

    fn __repr__(&self) -> String {
        format!("Vt.Matrix4dArray([{} items])", self.inner.len())
    }

    fn __str__(&self) -> String {
        format!("[{} Matrix4d]", self.inner.len())
    }
}

#[pyclass(name = "Matrix4fArray", module = "pxr.Vt")]
#[derive(Clone)]
pub struct PyMatrix4fArray {
    inner: Array<usd_gf::Matrix4f>,
}

#[pymethods]
impl PyMatrix4fArray {
    #[new]
    #[pyo3(signature = (arg = None))]
    fn new(arg: Option<&Bound<'_, PyAny>>) -> PyResult<Self> {
        let Some(obj) = arg else {
            return Ok(Self { inner: Array::new() });
        };
        if let Ok(n) = obj.extract::<usize>() {
            return Ok(Self {
                inner: Array::from_elem(usd_gf::Matrix4f::identity(), n),
            });
        }
        let items: Vec<Vec<f32>> = obj
            .extract()
            .map_err(|_| PyValueError::new_err("expected int size or list of 16-element float lists"))?;
        let mats: Vec<usd_gf::Matrix4f> = items
            .iter()
            .map(|flat| flat_to_mat4f(flat).ok_or_else(|| {
                PyValueError::new_err("each Matrix4f must be 16 floats")
            }))
            .collect::<PyResult<Vec<_>>>()?;
        Ok(Self { inner: Array::from(mats) })
    }

    fn __len__(&self) -> usize { self.inner.len() }

    fn __getitem__(&self, py: Python<'_>, key: &Bound<'_, PyAny>) -> PyResult<PyObject> {
        if let Ok(i) = key.extract::<isize>() {
            let idx = norm_idx(i, self.inner.len())?;
            let flat = mat4f_to_flat(&self.inner.as_slice()[idx]);
            Ok(flat.into_py(py))
        } else {
            Err(PyTypeError::new_err("index must be int"))
        }
    }

    fn __setitem__(&mut self, key: &Bound<'_, PyAny>, value: &Bound<'_, PyAny>) -> PyResult<()> {
        if let Ok(i) = key.extract::<isize>() {
            let idx = norm_idx(i, self.inner.len())?;
            let flat: Vec<f32> = value.extract()?;
            let m = flat_to_mat4f(&flat)
                .ok_or_else(|| PyValueError::new_err("Matrix4f requires 16 floats"))?;
            self.inner.make_unique();
            self.inner.as_mut_slice()[idx] = m;
            Ok(())
        } else {
            Err(PyTypeError::new_err("index must be int"))
        }
    }

    fn __iter__(slf: PyRef<'_, Self>) -> PyResult<Py<VtStringIter>> {
        let data: Vec<String> = slf.inner.as_slice()
            .iter()
            .map(|m| format!("{:?}", mat4f_to_flat(m)))
            .collect();
        Py::new(slf.py(), VtStringIter { data, pos: 0 })
    }

    fn __eq__(&self, other: &Self) -> bool {
        self.inner.as_slice() == other.inner.as_slice()
    }

    fn __ne__(&self, other: &Self) -> bool {
        self.inner.as_slice() != other.inner.as_slice()
    }

    fn __repr__(&self) -> String {
        format!("Vt.Matrix4fArray([{} items])", self.inner.len())
    }

    fn __str__(&self) -> String {
        format!("[{} Matrix4f]", self.inner.len())
    }
}

// ============================================================================
// VtDictionary ↔ Python dict
// ============================================================================

/// Converts a Rust `Dictionary` to a Python `dict` recursively.
///
/// String keys are preserved; `Value` payloads are converted to the closest
/// Python type.  Nested dictionaries become nested dicts.
pub fn dict_to_py(py: Python<'_>, d: &Dictionary) -> PyResult<PyObject> {
    let dict = PyDict::new(py);
    for (k, v) in d.iter() {
        let py_val = value_to_py(py, v)?;
        dict.set_item(k, py_val)?;
    }
    Ok(dict.into())
}

/// Converts a Python object to a `Value`.
///
/// Supports: `None`, `bool`, `int`, `float`, `str`, `dict` (→ `Dictionary`).
pub fn py_to_value(obj: &Bound<'_, PyAny>) -> PyResult<Value> {
    if obj.is_none() {
        return Ok(Value::empty());
    }
    if let Ok(b) = obj.extract::<bool>() {
        return Ok(Value::new(b));
    }
    if let Ok(i) = obj.extract::<i64>() {
        if i >= i64::from(i32::MIN) && i <= i64::from(i32::MAX) {
            return Ok(Value::new(i as i32));
        }
        return Ok(Value::new(i));
    }
    if let Ok(f) = obj.extract::<f64>() {
        return Ok(Value::from_f64(f));
    }
    if let Ok(s) = obj.extract::<String>() {
        return Ok(Value::new(s));
    }
    if let Ok(d) = obj.downcast::<PyDict>() {
        let dict = py_dict_to_dict(d)?;
        return Ok(Value::from_dictionary(dict.to_hash_map()));
    }
    // Unknown Python object → empty value (safe fallback)
    Ok(Value::empty())
}

/// Converts a Python `dict` to a `Dictionary`.
fn py_dict_to_dict(d: &Bound<'_, PyDict>) -> PyResult<Dictionary> {
    let mut dict = Dictionary::new();
    for (k, v) in d.iter() {
        let key: String = k
            .extract()
            .map_err(|_| PyTypeError::new_err("VtDictionary keys must be strings"))?;
        let val = py_to_value(&v)?;
        dict.insert_value(key, val);
    }
    Ok(dict)
}

/// Renders a `Value` as a Python object.
fn value_to_py(py: Python<'_>, v: &Value) -> PyResult<PyObject> {
    if v.is_empty() {
        return Ok(py.None());
    }
    if let Some(b) = v.get::<bool>() {
        return Ok(b.into_py(py));
    }
    if let Some(i) = v.get::<i32>() {
        return Ok(i.into_py(py));
    }
    if let Some(i) = v.get::<i64>() {
        return Ok(i.into_py(py));
    }
    if let Some(u) = v.get::<u64>() {
        return Ok(u.into_py(py));
    }
    if let Some(x) = v.get::<f64>() {
        return Ok(x.into_py(py));
    }
    if let Some(x) = v.get::<f32>() {
        return Ok(((*x) as f64).into_py(py));
    }
    if let Some(s) = v.get::<String>() {
        return Ok(s.into_py(py));
    }
    if let Some(t) = v.get::<usd_tf::Token>() {
        return Ok(t.to_string().into_py(py));
    }
    if let Some(dict) = v.get::<usd_vt::Dictionary>() {
        return dict_to_py(py, dict);
    }
    // Fall back to None for unrecognized types
    Ok(py.None())
}

/// Python-facing `VtDictionary` class — thin wrapper that round-trips as a Python dict.
///
/// In C++ pxr, `VtDictionary` is typically passed as a plain `dict` in Python.
/// We provide the class for explicit construction and `__repr__` fidelity.
#[pyclass(name = "Dictionary", module = "pxr.Vt")]
#[derive(Clone, Default)]
pub struct PyDictionary {
    inner: Dictionary,
}

#[pymethods]
impl PyDictionary {
    #[new]
    #[pyo3(signature = (d = None))]
    fn new(d: Option<&Bound<'_, PyDict>>) -> PyResult<Self> {
        let inner = match d {
            Some(py_dict) => py_dict_to_dict(py_dict)?,
            None => Dictionary::new(),
        };
        Ok(Self { inner })
    }

    /// Convert to a plain Python `dict`.
    #[pyo3(name = "AsDict")]
    fn as_dict(&self, py: Python<'_>) -> PyResult<PyObject> {
        dict_to_py(py, &self.inner)
    }

    fn __len__(&self) -> usize { self.inner.len() }

    fn __repr__(&self, py: Python<'_>) -> PyResult<String> {
        let d = dict_to_py(py, &self.inner)?;
        Ok(format!("Vt.Dictionary({})", d.bind(py)))
    }

    fn __str__(&self, py: Python<'_>) -> PyResult<String> {
        let d = dict_to_py(py, &self.inner)?;
        Ok(format!("{}", d.bind(py)))
    }

    fn __getitem__(&self, py: Python<'_>, key: &str) -> PyResult<PyObject> {
        self.inner
            .get(key)
            .ok_or_else(|| PyKeyError::new_err(key.to_owned()))
            .and_then(|v| value_to_py(py, v))
    }

    fn __setitem__(&mut self, key: &str, value: &Bound<'_, PyAny>) -> PyResult<()> {
        let v = py_to_value(value)?;
        self.inner.insert_value(key.to_owned(), v);
        Ok(())
    }

    fn __contains__(&self, key: &str) -> bool {
        self.inner.contains_key(key)
    }

    fn __eq__(&self, other: &Self) -> bool {
        self.inner == other.inner
    }

    fn __ne__(&self, other: &Self) -> bool {
        self.inner != other.inner
    }

    fn keys(&self) -> Vec<String> {
        self.inner.keys().map(|k| k.to_owned()).collect()
    }
}

use pyo3::exceptions::PyKeyError;

// ============================================================================
// Module registration
// ============================================================================

/// Register all `pxr.Vt` classes into the submodule.
pub fn register(py: Python<'_>, m: &Bound<'_, PyModule>) -> PyResult<()> {
    let _ = py;

    // Value / _ValueWrapper
    m.add_class::<PyValue>()?;

    // Dictionary
    m.add_class::<PyDictionary>()?;

    // Scalar arrays
    m.add_class::<PyBoolArray>()?;
    m.add_class::<PyUCharArray>()?;
    m.add_class::<PyShortArray>()?;
    m.add_class::<PyUShortArray>()?;
    m.add_class::<PyIntArray>()?;
    m.add_class::<PyUIntArray>()?;
    m.add_class::<PyInt64Array>()?;
    m.add_class::<PyUInt64Array>()?;
    m.add_class::<PyFloatArray>()?;
    m.add_class::<PyDoubleArray>()?;
    m.add_class::<PyHalfArray>()?;

    // String / Token arrays
    m.add_class::<PyStringArray>()?;
    m.add_class::<PyTokenArray>()?;

    // Vec arrays
    m.add_class::<PyVec2fArray>()?;
    m.add_class::<PyVec3fArray>()?;
    m.add_class::<PyVec4fArray>()?;
    m.add_class::<PyVec2dArray>()?;
    m.add_class::<PyVec3dArray>()?;
    m.add_class::<PyVec4dArray>()?;
    m.add_class::<PyVec2iArray>()?;
    m.add_class::<PyVec3iArray>()?;
    m.add_class::<PyVec4iArray>()?;

    // Matrix arrays
    m.add_class::<PyMatrix4dArray>()?;
    m.add_class::<PyMatrix4fArray>()?;

    // Scalar iterators (concrete per-type, no generics allowed in PyO3)
    m.add_class::<VtBoolIter>()?;
    m.add_class::<VtI32Iter>()?;
    m.add_class::<VtU32Iter>()?;
    m.add_class::<VtI64Iter>()?;
    m.add_class::<VtU64Iter>()?;
    m.add_class::<VtI8Iter>()?;
    m.add_class::<VtU8Iter>()?;
    m.add_class::<VtI16Iter>()?;
    m.add_class::<VtU16Iter>()?;
    m.add_class::<VtF32Iter>()?;
    m.add_class::<VtF64Iter>()?;
    m.add_class::<VtStringIter>()?;

    Ok(())
}
