//! BSDF framework — base types for bidirectional scattering distribution functions.
//!
//! Port of `libbsdl` from OSL/SPI. Provides:
//! - Base BSDF trait (evaluate, sample, pdf)
//! - Lambertian diffuse
//! - Oren-Nayar rough diffuse
//! - Microfacet (GGX/Beckmann) distributions
//! - Reflection/refraction/transparent

use crate::Float;
use crate::math::{Color3, Vec3};

/// A sample generated by BSDF sampling.
#[derive(Debug, Clone, Copy)]
pub struct BSDFSample {
    /// Sampled direction.
    pub wi: Vec3,
    /// BSDF value * cos(theta) / pdf.
    pub weight: Color3,
    /// Probability density.
    pub pdf: Float,
    /// Whether this is a reflection or transmission.
    pub is_reflection: bool,
}

/// BSDF evaluation result.
#[derive(Debug, Clone, Copy)]
pub struct BSDFEval {
    /// BSDF value.
    pub f: Color3,
    /// Probability density for this direction.
    pub pdf: Float,
}

/// Base BSDF trait.
pub trait BSDF: Send + Sync {
    /// Evaluate the BSDF for given incoming (wi) and outgoing (wo) directions.
    /// Normal N is assumed to be (0, 0, 1) in shading space.
    fn eval(&self, wo: Vec3, wi: Vec3) -> BSDFEval;

    /// Sample the BSDF given outgoing direction and two random numbers.
    fn sample(&self, wo: Vec3, randu: Float, randv: Float) -> Option<BSDFSample>;

    /// Probability of sampling direction wi given wo.
    fn pdf(&self, wo: Vec3, wi: Vec3) -> Float;
}

// ---------------------------------------------------------------------------
// Utility functions
// ---------------------------------------------------------------------------

const INV_PI: Float = std::f32::consts::FRAC_1_PI;
const PI: Float = std::f32::consts::PI;

/// Cosine-weighted hemisphere sampling.
pub fn sample_cosine_hemisphere(randu: Float, randv: Float) -> Vec3 {
    let r = randu.sqrt();
    let phi = 2.0 * PI * randv;
    let x = r * phi.cos();
    let y = r * phi.sin();
    let z = (1.0 - randu).max(0.0).sqrt();
    Vec3::new(x, y, z)
}

/// Uniform hemisphere sampling.
pub fn sample_uniform_hemisphere(randu: Float, randv: Float) -> Vec3 {
    let z = randu;
    let r = (1.0 - z * z).max(0.0).sqrt();
    let phi = 2.0 * PI * randv;
    Vec3::new(r * phi.cos(), r * phi.sin(), z)
}

/// Reflect direction around normal.
#[inline]
pub fn reflect(wo: Vec3, n: Vec3) -> Vec3 {
    let d = 2.0 * wo.dot(n);
    Vec3::new(d * n.x - wo.x, d * n.y - wo.y, d * n.z - wo.z)
}

/// Refract direction. Returns None for total internal reflection.
pub fn refract(wo: Vec3, n: Vec3, eta: Float) -> Option<Vec3> {
    let cos_theta_i = wo.dot(n);
    let sin2_theta_i = (1.0 - cos_theta_i * cos_theta_i).max(0.0);
    let sin2_theta_t = eta * eta * sin2_theta_i;
    if sin2_theta_t >= 1.0 {
        return None; // total internal reflection
    }
    let cos_theta_t = (1.0 - sin2_theta_t).sqrt();
    Some(Vec3::new(
        eta * (-wo.x) + (eta * cos_theta_i - cos_theta_t) * n.x,
        eta * (-wo.y) + (eta * cos_theta_i - cos_theta_t) * n.y,
        eta * (-wo.z) + (eta * cos_theta_i - cos_theta_t) * n.z,
    ))
}

/// Fresnel reflectance (Schlick approximation).
#[inline]
pub fn fresnel_schlick(cos_theta: Float, f0: Float) -> Float {
    let t = (1.0 - cos_theta).max(0.0);
    let t2 = t * t;
    f0 + (1.0 - f0) * t2 * t2 * t
}

/// Full Fresnel for dielectrics.
pub fn fresnel_dielectric(cos_theta_i: Float, eta: Float) -> Float {
    let cos_i = cos_theta_i.abs().min(1.0);
    let sin2_t = eta * eta * (1.0 - cos_i * cos_i);
    if sin2_t >= 1.0 {
        return 1.0; // total internal reflection
    }
    let cos_t = (1.0 - sin2_t).sqrt();
    let r_parl = (eta * cos_i - cos_t) / (eta * cos_i + cos_t);
    let r_perp = (cos_i - eta * cos_t) / (cos_i + eta * cos_t);
    0.5 * (r_parl * r_parl + r_perp * r_perp)
}

// ---------------------------------------------------------------------------
// Lambertian diffuse
// ---------------------------------------------------------------------------

/// Lambertian (perfectly diffuse) BSDF.
pub struct Diffuse {
    pub albedo: Color3,
}

impl Diffuse {
    pub fn new(albedo: Color3) -> Self {
        Self { albedo }
    }
}

impl BSDF for Diffuse {
    fn eval(&self, _wo: Vec3, wi: Vec3) -> BSDFEval {
        let cos_theta = wi.z.max(0.0);
        BSDFEval {
            f: self.albedo * INV_PI,
            pdf: cos_theta * INV_PI,
        }
    }

    fn sample(&self, _wo: Vec3, randu: Float, randv: Float) -> Option<BSDFSample> {
        let wi = sample_cosine_hemisphere(randu, randv);
        let cos_theta = wi.z.max(0.0);
        if cos_theta <= 0.0 {
            return None;
        }

        Some(BSDFSample {
            wi,
            weight: self.albedo,
            pdf: cos_theta * INV_PI,
            is_reflection: true,
        })
    }

    fn pdf(&self, _wo: Vec3, wi: Vec3) -> Float {
        wi.z.max(0.0) * INV_PI
    }
}

// ---------------------------------------------------------------------------
// Oren-Nayar rough diffuse
// ---------------------------------------------------------------------------

/// Oren-Nayar rough diffuse BSDF.
pub struct OrenNayar {
    pub albedo: Color3,
    pub sigma: Float, // roughness (0 = Lambertian)
    // Precomputed coefficients
    a: Float,
    b: Float,
}

impl OrenNayar {
    pub fn new(albedo: Color3, sigma: Float) -> Self {
        let sigma2 = sigma * sigma;
        let a = 1.0 - 0.5 * sigma2 / (sigma2 + 0.33);
        let b = 0.45 * sigma2 / (sigma2 + 0.09);
        Self {
            albedo,
            sigma,
            a,
            b,
        }
    }
}

impl BSDF for OrenNayar {
    fn eval(&self, wo: Vec3, wi: Vec3) -> BSDFEval {
        let n_dot_wo = wo.z.max(0.0);
        let n_dot_wi = wi.z.max(0.0);

        if n_dot_wo <= 0.0 || n_dot_wi <= 0.0 {
            return BSDFEval {
                f: Color3::ZERO,
                pdf: 0.0,
            };
        }

        let theta_o = n_dot_wo.acos();
        let theta_i = n_dot_wi.acos();
        let alpha = theta_o.max(theta_i);
        let beta = theta_o.min(theta_i);

        // Compute cos(phi_i - phi_o)
        let sin_theta_o = (1.0 - n_dot_wo * n_dot_wo).max(0.0).sqrt();
        let sin_theta_i = (1.0 - n_dot_wi * n_dot_wi).max(0.0).sqrt();
        let cos_dphi = if sin_theta_o > 1e-6 && sin_theta_i > 1e-6 {
            let dphi = (wo.x * wi.x + wo.y * wi.y) / (sin_theta_o * sin_theta_i);
            dphi.clamp(-1.0, 1.0)
        } else {
            1.0
        };

        let oren_nayar = self.a + self.b * cos_dphi.max(0.0) * alpha.sin() * beta.tan();

        BSDFEval {
            f: self.albedo * (oren_nayar * INV_PI),
            pdf: n_dot_wi * INV_PI,
        }
    }

    fn sample(&self, wo: Vec3, randu: Float, randv: Float) -> Option<BSDFSample> {
        let wi = sample_cosine_hemisphere(randu, randv);
        let eval = self.eval(wo, wi);
        if eval.pdf <= 0.0 {
            return None;
        }

        Some(BSDFSample {
            wi,
            weight: eval.f * (wi.z.max(0.0) / eval.pdf),
            pdf: eval.pdf,
            is_reflection: true,
        })
    }

    fn pdf(&self, _wo: Vec3, wi: Vec3) -> Float {
        wi.z.max(0.0) * INV_PI
    }
}

// ---------------------------------------------------------------------------
// Microfacet (GGX)
// ---------------------------------------------------------------------------

/// GGX microfacet distribution.
pub struct GGXDistribution {
    pub alpha: Float,
}

impl GGXDistribution {
    pub fn new(roughness: Float) -> Self {
        Self {
            alpha: roughness * roughness,
        }
    }

    /// GGX NDF: D(m) = alpha^2 / (pi * (cos^2(theta) * (alpha^2 - 1) + 1)^2)
    pub fn d(&self, cos_theta: Float) -> Float {
        let a2 = self.alpha * self.alpha;
        let denom = cos_theta * cos_theta * (a2 - 1.0) + 1.0;
        a2 / (PI * denom * denom)
    }

    /// Smith G1 term for GGX.
    pub fn g1(&self, cos_theta: Float) -> Float {
        let a2 = self.alpha * self.alpha;
        let cos2 = cos_theta * cos_theta;
        2.0 * cos_theta / (cos_theta + (a2 + (1.0 - a2) * cos2).sqrt())
    }

    /// Smith G term (separable).
    pub fn g(&self, cos_theta_o: Float, cos_theta_i: Float) -> Float {
        self.g1(cos_theta_o) * self.g1(cos_theta_i)
    }

    /// Sample the GGX distribution (importance sample the NDF).
    pub fn sample_half(&self, randu: Float, randv: Float) -> Vec3 {
        let a2 = self.alpha * self.alpha;
        let cos_theta = ((1.0 - randu) / (randu * (a2 - 1.0) + 1.0)).sqrt();
        let sin_theta = (1.0 - cos_theta * cos_theta).max(0.0).sqrt();
        let phi = 2.0 * PI * randv;
        Vec3::new(sin_theta * phi.cos(), sin_theta * phi.sin(), cos_theta)
    }
}

/// Microfacet reflection BSDF (GGX + Schlick Fresnel).
pub struct MicrofacetReflection {
    pub color: Color3,
    pub dist: GGXDistribution,
    pub f0: Float,
}

impl MicrofacetReflection {
    pub fn new(color: Color3, roughness: Float, f0: Float) -> Self {
        Self {
            color,
            dist: GGXDistribution::new(roughness),
            f0,
        }
    }
}

impl BSDF for MicrofacetReflection {
    fn eval(&self, wo: Vec3, wi: Vec3) -> BSDFEval {
        let cos_o = wo.z;
        let cos_i = wi.z;
        if cos_o <= 0.0 || cos_i <= 0.0 {
            return BSDFEval {
                f: Color3::ZERO,
                pdf: 0.0,
            };
        }

        let h = (wo + wi).normalize();
        let n_dot_h = h.z;
        let wo_dot_h = wo.dot(h);

        let d = self.dist.d(n_dot_h);
        let g = self.dist.g(cos_o, cos_i);
        let f = fresnel_schlick(wo_dot_h, self.f0);

        let spec = d * g * f / (4.0 * cos_o * cos_i);

        BSDFEval {
            f: self.color * spec,
            pdf: d * n_dot_h / (4.0 * wo_dot_h),
        }
    }

    fn sample(&self, wo: Vec3, randu: Float, randv: Float) -> Option<BSDFSample> {
        if wo.z <= 0.0 {
            return None;
        }

        let h = self.dist.sample_half(randu, randv);
        let wi = reflect(wo, h);
        if wi.z <= 0.0 {
            return None;
        }

        let eval = self.eval(wo, wi);
        if eval.pdf <= 0.0 {
            return None;
        }

        Some(BSDFSample {
            wi,
            weight: eval.f * (wi.z / eval.pdf),
            pdf: eval.pdf,
            is_reflection: true,
        })
    }

    fn pdf(&self, wo: Vec3, wi: Vec3) -> Float {
        if wo.z <= 0.0 || wi.z <= 0.0 {
            return 0.0;
        }
        let h = (wo + wi).normalize();
        let d = self.dist.d(h.z);
        d * h.z / (4.0 * wo.dot(h))
    }
}

// ---------------------------------------------------------------------------
// Transparent / passthrough
// ---------------------------------------------------------------------------

/// Transparent BSDF — passes through with no scattering.
pub struct Transparent;

impl BSDF for Transparent {
    fn eval(&self, _wo: Vec3, _wi: Vec3) -> BSDFEval {
        BSDFEval {
            f: Color3::ZERO,
            pdf: 0.0,
        }
    }

    fn sample(&self, wo: Vec3, _randu: Float, _randv: Float) -> Option<BSDFSample> {
        Some(BSDFSample {
            wi: Vec3::new(-wo.x, -wo.y, -wo.z),
            weight: Color3::splat(1.0),
            pdf: 1.0,
            is_reflection: false,
        })
    }

    fn pdf(&self, _wo: Vec3, _wi: Vec3) -> Float {
        0.0
    }
}

// ---------------------------------------------------------------------------
// Emission
// ---------------------------------------------------------------------------

/// Emission "BSDF" — uniform radiance in all directions.
/// Matches the `emission()` closure in OSL.
#[derive(Debug, Clone)]
pub struct Emission {
    pub radiance: Color3,
}

impl Default for Emission {
    fn default() -> Self {
        Self {
            radiance: Color3::new(1.0, 1.0, 1.0),
        }
    }
}

impl BSDF for Emission {
    fn eval(&self, _wo: Vec3, _wi: Vec3) -> BSDFEval {
        // Emission is uniform over the hemisphere
        BSDFEval {
            f: self.radiance,
            pdf: 1.0 / (2.0 * PI),
        }
    }

    fn sample(&self, _wo: Vec3, randu: Float, randv: Float) -> Option<BSDFSample> {
        let wi = sample_uniform_hemisphere(randu, randv);
        let pdf = 1.0 / (2.0 * PI);
        Some(BSDFSample {
            wi,
            weight: Color3::new(
                self.radiance.x / pdf,
                self.radiance.y / pdf,
                self.radiance.z / pdf,
            ),
            pdf,
            is_reflection: true,
        })
    }

    fn pdf(&self, _wo: Vec3, _wi: Vec3) -> Float {
        1.0 / (2.0 * PI)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_diffuse_eval() {
        let d = Diffuse::new(Color3::splat(1.0));
        let wo = Vec3::new(0.0, 0.0, 1.0);
        let wi = Vec3::new(0.0, 0.0, 1.0);
        let eval = d.eval(wo, wi);
        assert!(eval.f.x > 0.0);
        assert!(eval.pdf > 0.0);
    }

    #[test]
    fn test_diffuse_sample() {
        let d = Diffuse::new(Color3::splat(0.8));
        let wo = Vec3::new(0.0, 0.0, 1.0);
        let sample = d.sample(wo, 0.5, 0.5);
        assert!(sample.is_some());
        let s = sample.unwrap();
        assert!(s.wi.z > 0.0);
        assert!(s.pdf > 0.0);
    }

    #[test]
    fn test_oren_nayar() {
        let on = OrenNayar::new(Color3::splat(0.8), 0.5);
        let wo = Vec3::new(0.0, 0.0, 1.0);
        let wi = Vec3::new(0.3, 0.0, 0.9).normalize();
        let eval = on.eval(wo, wi);
        assert!(eval.f.x > 0.0);
    }

    #[test]
    fn test_ggx_ndf() {
        let dist = GGXDistribution::new(0.5);
        // At normal incidence, D should be high
        let d0 = dist.d(1.0);
        let d45 = dist.d(0.707);
        assert!(d0 > d45);
    }

    #[test]
    fn test_microfacet_sample() {
        let mf = MicrofacetReflection::new(Color3::splat(1.0), 0.3, 0.04);
        let wo = Vec3::new(0.0, 0.0, 1.0);
        let sample = mf.sample(wo, 0.3, 0.7);
        assert!(sample.is_some());
    }

    #[test]
    fn test_fresnel() {
        // At normal incidence with f0=0.04
        let f = fresnel_schlick(1.0, 0.04);
        assert!((f - 0.04).abs() < 0.001);

        // At grazing angle
        let f = fresnel_schlick(0.0, 0.04);
        assert!((f - 1.0).abs() < 0.001);
    }

    #[test]
    fn test_transparent() {
        let t = Transparent;
        let wo = Vec3::new(0.3, 0.2, 0.9).normalize();
        let s = t.sample(wo, 0.0, 0.0).unwrap();
        // Should pass straight through
        assert!((s.wi.x + wo.x).abs() < 1e-5);
        assert!((s.wi.y + wo.y).abs() < 1e-5);
    }

    #[test]
    fn test_refract() {
        let wo = Vec3::new(0.0, 0.0, 1.0);
        let n = Vec3::new(0.0, 0.0, 1.0);
        // Refraction with eta=1 should pass straight through
        let wi = refract(wo, n, 1.0).unwrap();
        assert!((wi.z + 1.0).abs() < 1e-5 || (wi.z - (-1.0)).abs() < 1e-5);
    }
}
