//! Example: Writing a USDA layer with metadata
//!
//! This example demonstrates how to create a Layer, set metadata,
//! and export it to USDA text format.

use usd::sdf::Layer;
use usd::tf::Token;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("Creating a new USD layer...\n");

    // Create an anonymous layer
    let layer = Layer::create_anonymous(Some("example"));

    // Set layer metadata
    layer.set_default_prim(&Token::new("World"));
    layer.set_documentation("Example USD layer demonstrating USDA export");
    layer.set_comment("Generated by usd-rs write example");

    // Set time-related metadata
    layer.set_start_time_code(1.0);
    layer.set_end_time_code(240.0);
    layer.set_time_codes_per_second(24.0);
    layer.set_frames_per_second(24.0);

    // Set authoring metadata
    layer.set_owner("usd-rs");

    // Export to USDA string
    let usda_content = layer.export_to_string()?;

    println!("Exported USDA content:");
    println!("{}", "=".repeat(60));
    println!("{}", usda_content);
    println!("{}", "=".repeat(60));

    // Optionally save to file
    // std::fs::write("example.usda", &usda_content)?;
    // println!("\nSaved to example.usda");

    Ok(())
}
